unit ShdFeaturesShader.M;
(*
  #version:1# (machine generated, don't edit!)

  Generated by sokol-shdc (https://github.com/floooh/sokol-tools)

  Cmdline:
    sokol-shdc --input ShdFeaturesShader.glsl --output ShdFeaturesShader.M.pas --defines MATERIAL --module m --reflection

  Overview:
  =========
  Shader program: 'prog':
    Get shader desc: Mprog_shader_desc(sg_query_backend());
    Vertex Shader: vs
    Fragment Shader: fs
    Attributes:
      ATTR_M_PROG_POSITION => 0
      ATTR_M_PROG_NORMAL => 1
  Bindings:
    Uniform block 'vs_params':
      C struct: TMVSParams
      Bind slot: UB_M_VS_PARAMS => 0
    Uniform block 'phong_params':
      C struct: TMPhongParams
      Bind slot: UB_M_PHONG_PARAMS => 1
*)

{$INCLUDE 'Neslib.Sokol.inc'}

interface

uses
  Neslib.FastMath,
  Neslib.Sokol.Gfx;

const
  ATTR_M_PROG_POSITION = 0;
  ATTR_M_PROG_NORMAL = 1;

const
  UB_M_VS_PARAMS = 0;
  UB_M_PHONG_PARAMS = 1;

type
  TMVSParams = packed record
  public
    Mvp: TMatrix4;
    Model: TMatrix4;
  end align 16;

type
  TMPhongParams = packed record
  public
    MatDiffuse: TVector3;
    _Pad12: array [0..3] of Byte;
    MatSpecular: TVector3;
    MatSpecPower: Single;
  end align 16;

function MProgShaderDesc: PNativeShaderDesc;

function MProgAttrSlot(const AAttrName: String): Integer; inline;
function MProgTextureSlot(const ATexName: String): Integer; inline;
function MProgSamplerSlot(const ASmpName: String): Integer; inline;
function MProgUniformBlockSlot(const AUBName: String): Integer; inline;
function MProgUniformBlockSize(const AUBName: String): NativeInt; inline;
function MProgUniformOffset(const AUBName, AUName: String): Integer; inline;
function MProgUniformDesc(const AUBName, AUName: String): TGlslShaderUniform; inline;
function MProgStorageBufferSlot(const ASBufName: String): Integer; inline;
function MProgStorageImageSlot(const ASImgName: String): Integer; inline;

implementation

uses
  Neslib.Sokol.Api;

(*
  #version 410

  uniform vec4 vs_params[8];
  layout(location = 0) in vec4 position;
  layout(location = 1) in vec3 normal;

  void main()
  {
      gl_Position = mat4(vs_params[0], vs_params[1], vs_params[2], vs_params[3]) * position;
  }

*)
{$IFDEF SOKOL_GLCORE}
const
  MVS_SOURCE_GLSL410: array [0..226] of Byte = (
    $23,$76,$65,$72,$73,$69,$6f,$6e,$20,$34,$31,$30,$0a,$0a,$75,$6e,
    $69,$66,$6f,$72,$6d,$20,$76,$65,$63,$34,$20,$76,$73,$5f,$70,$61,
    $72,$61,$6d,$73,$5b,$38,$5d,$3b,$0a,$6c,$61,$79,$6f,$75,$74,$28,
    $6c,$6f,$63,$61,$74,$69,$6f,$6e,$20,$3d,$20,$30,$29,$20,$69,$6e,
    $20,$76,$65,$63,$34,$20,$70,$6f,$73,$69,$74,$69,$6f,$6e,$3b,$0a,
    $6c,$61,$79,$6f,$75,$74,$28,$6c,$6f,$63,$61,$74,$69,$6f,$6e,$20,
    $3d,$20,$31,$29,$20,$69,$6e,$20,$76,$65,$63,$33,$20,$6e,$6f,$72,
    $6d,$61,$6c,$3b,$0a,$0a,$76,$6f,$69,$64,$20,$6d,$61,$69,$6e,$28,
    $29,$0a,$7b,$0a,$20,$20,$20,$20,$67,$6c,$5f,$50,$6f,$73,$69,$74,
    $69,$6f,$6e,$20,$3d,$20,$6d,$61,$74,$34,$28,$76,$73,$5f,$70,$61,
    $72,$61,$6d,$73,$5b,$30,$5d,$2c,$20,$76,$73,$5f,$70,$61,$72,$61,
    $6d,$73,$5b,$31,$5d,$2c,$20,$76,$73,$5f,$70,$61,$72,$61,$6d,$73,
    $5b,$32,$5d,$2c,$20,$76,$73,$5f,$70,$61,$72,$61,$6d,$73,$5b,$33,
    $5d,$29,$20,$2a,$20,$70,$6f,$73,$69,$74,$69,$6f,$6e,$3b,$0a,$7d,
    $0a,$0a,$00);
{$ENDIF}

(*
  #version 410

  uniform vec4 phong_params[2];
  layout(location = 0) out vec4 frag_color;

  void main()
  {
      frag_color = vec4(phong_params[0].xyz, 1.0);
  }

*)
{$IFDEF SOKOL_GLCORE}
const
  MFS_SOURCE_GLSL410: array [0..153] of Byte = (
    $23,$76,$65,$72,$73,$69,$6f,$6e,$20,$34,$31,$30,$0a,$0a,$75,$6e,
    $69,$66,$6f,$72,$6d,$20,$76,$65,$63,$34,$20,$70,$68,$6f,$6e,$67,
    $5f,$70,$61,$72,$61,$6d,$73,$5b,$32,$5d,$3b,$0a,$6c,$61,$79,$6f,
    $75,$74,$28,$6c,$6f,$63,$61,$74,$69,$6f,$6e,$20,$3d,$20,$30,$29,
    $20,$6f,$75,$74,$20,$76,$65,$63,$34,$20,$66,$72,$61,$67,$5f,$63,
    $6f,$6c,$6f,$72,$3b,$0a,$0a,$76,$6f,$69,$64,$20,$6d,$61,$69,$6e,
    $28,$29,$0a,$7b,$0a,$20,$20,$20,$20,$66,$72,$61,$67,$5f,$63,$6f,
    $6c,$6f,$72,$20,$3d,$20,$76,$65,$63,$34,$28,$70,$68,$6f,$6e,$67,
    $5f,$70,$61,$72,$61,$6d,$73,$5b,$30,$5d,$2e,$78,$79,$7a,$2c,$20,
    $31,$2e,$30,$29,$3b,$0a,$7d,$0a,$0a,$00);
{$ENDIF}

(*
  #version 300 es

  uniform vec4 vs_params[8];
  layout(location = 0) in vec4 position;
  layout(location = 1) in vec3 normal;

  void main()
  {
      gl_Position = mat4(vs_params[0], vs_params[1], vs_params[2], vs_params[3]) * position;
  }

*)
{$IFDEF SOKOL_GLES3}
const
  MVS_SOURCE_GLSL300ES: array [0..229] of Byte = (
    $23,$76,$65,$72,$73,$69,$6f,$6e,$20,$33,$30,$30,$20,$65,$73,$0a,
    $0a,$75,$6e,$69,$66,$6f,$72,$6d,$20,$76,$65,$63,$34,$20,$76,$73,
    $5f,$70,$61,$72,$61,$6d,$73,$5b,$38,$5d,$3b,$0a,$6c,$61,$79,$6f,
    $75,$74,$28,$6c,$6f,$63,$61,$74,$69,$6f,$6e,$20,$3d,$20,$30,$29,
    $20,$69,$6e,$20,$76,$65,$63,$34,$20,$70,$6f,$73,$69,$74,$69,$6f,
    $6e,$3b,$0a,$6c,$61,$79,$6f,$75,$74,$28,$6c,$6f,$63,$61,$74,$69,
    $6f,$6e,$20,$3d,$20,$31,$29,$20,$69,$6e,$20,$76,$65,$63,$33,$20,
    $6e,$6f,$72,$6d,$61,$6c,$3b,$0a,$0a,$76,$6f,$69,$64,$20,$6d,$61,
    $69,$6e,$28,$29,$0a,$7b,$0a,$20,$20,$20,$20,$67,$6c,$5f,$50,$6f,
    $73,$69,$74,$69,$6f,$6e,$20,$3d,$20,$6d,$61,$74,$34,$28,$76,$73,
    $5f,$70,$61,$72,$61,$6d,$73,$5b,$30,$5d,$2c,$20,$76,$73,$5f,$70,
    $61,$72,$61,$6d,$73,$5b,$31,$5d,$2c,$20,$76,$73,$5f,$70,$61,$72,
    $61,$6d,$73,$5b,$32,$5d,$2c,$20,$76,$73,$5f,$70,$61,$72,$61,$6d,
    $73,$5b,$33,$5d,$29,$20,$2a,$20,$70,$6f,$73,$69,$74,$69,$6f,$6e,
    $3b,$0a,$7d,$0a,$0a,$00);
{$ENDIF}

(*
  #version 300 es
  precision mediump float;
  precision highp int;

  uniform highp vec4 phong_params[2];
  layout(location = 0) out highp vec4 frag_color;

  void main()
  {
      frag_color = vec4(phong_params[0].xyz, 1.0);
  }

*)
{$IFDEF SOKOL_GLES3}
const
  MFS_SOURCE_GLSL300ES: array [0..214] of Byte = (
    $23,$76,$65,$72,$73,$69,$6f,$6e,$20,$33,$30,$30,$20,$65,$73,$0a,
    $70,$72,$65,$63,$69,$73,$69,$6f,$6e,$20,$6d,$65,$64,$69,$75,$6d,
    $70,$20,$66,$6c,$6f,$61,$74,$3b,$0a,$70,$72,$65,$63,$69,$73,$69,
    $6f,$6e,$20,$68,$69,$67,$68,$70,$20,$69,$6e,$74,$3b,$0a,$0a,$75,
    $6e,$69,$66,$6f,$72,$6d,$20,$68,$69,$67,$68,$70,$20,$76,$65,$63,
    $34,$20,$70,$68,$6f,$6e,$67,$5f,$70,$61,$72,$61,$6d,$73,$5b,$32,
    $5d,$3b,$0a,$6c,$61,$79,$6f,$75,$74,$28,$6c,$6f,$63,$61,$74,$69,
    $6f,$6e,$20,$3d,$20,$30,$29,$20,$6f,$75,$74,$20,$68,$69,$67,$68,
    $70,$20,$76,$65,$63,$34,$20,$66,$72,$61,$67,$5f,$63,$6f,$6c,$6f,
    $72,$3b,$0a,$0a,$76,$6f,$69,$64,$20,$6d,$61,$69,$6e,$28,$29,$0a,
    $7b,$0a,$20,$20,$20,$20,$66,$72,$61,$67,$5f,$63,$6f,$6c,$6f,$72,
    $20,$3d,$20,$76,$65,$63,$34,$28,$70,$68,$6f,$6e,$67,$5f,$70,$61,
    $72,$61,$6d,$73,$5b,$30,$5d,$2e,$78,$79,$7a,$2c,$20,$31,$2e,$30,
    $29,$3b,$0a,$7d,$0a,$0a,$00);
{$ENDIF}

(*
  cbuffer vs_params : register(b0)
  {
      row_major float4x4 _34_mvp : packoffset(c0);
      row_major float4x4 _34_model : packoffset(c4);
  };


  static float4 gl_Position;
  static float4 position;
  static float3 normal;

  struct SPIRV_Cross_Input
  {
      float4 position : TEXCOORD0;
      float3 normal : TEXCOORD1;
  };

  struct SPIRV_Cross_Output
  {
      float4 gl_Position : SV_Position;
  };

  void vert_main()
  {
      gl_Position = mul(position, _34_mvp);
  }

  SPIRV_Cross_Output main(SPIRV_Cross_Input stage_input)
  {
      position = stage_input.position;
      normal = stage_input.normal;
      vert_main();
      SPIRV_Cross_Output stage_output;
      stage_output.gl_Position = gl_Position;
      return stage_output;
  }
*)
{$IFDEF SOKOL_D3D11}
const
  MVS_SOURCE_HLSL5: array [0..695] of Byte = (
    $63,$62,$75,$66,$66,$65,$72,$20,$76,$73,$5f,$70,$61,$72,$61,$6d,
    $73,$20,$3a,$20,$72,$65,$67,$69,$73,$74,$65,$72,$28,$62,$30,$29,
    $0a,$7b,$0a,$20,$20,$20,$20,$72,$6f,$77,$5f,$6d,$61,$6a,$6f,$72,
    $20,$66,$6c,$6f,$61,$74,$34,$78,$34,$20,$5f,$33,$34,$5f,$6d,$76,
    $70,$20,$3a,$20,$70,$61,$63,$6b,$6f,$66,$66,$73,$65,$74,$28,$63,
    $30,$29,$3b,$0a,$20,$20,$20,$20,$72,$6f,$77,$5f,$6d,$61,$6a,$6f,
    $72,$20,$66,$6c,$6f,$61,$74,$34,$78,$34,$20,$5f,$33,$34,$5f,$6d,
    $6f,$64,$65,$6c,$20,$3a,$20,$70,$61,$63,$6b,$6f,$66,$66,$73,$65,
    $74,$28,$63,$34,$29,$3b,$0a,$7d,$3b,$0a,$0a,$0a,$73,$74,$61,$74,
    $69,$63,$20,$66,$6c,$6f,$61,$74,$34,$20,$67,$6c,$5f,$50,$6f,$73,
    $69,$74,$69,$6f,$6e,$3b,$0a,$73,$74,$61,$74,$69,$63,$20,$66,$6c,
    $6f,$61,$74,$34,$20,$70,$6f,$73,$69,$74,$69,$6f,$6e,$3b,$0a,$73,
    $74,$61,$74,$69,$63,$20,$66,$6c,$6f,$61,$74,$33,$20,$6e,$6f,$72,
    $6d,$61,$6c,$3b,$0a,$0a,$73,$74,$72,$75,$63,$74,$20,$53,$50,$49,
    $52,$56,$5f,$43,$72,$6f,$73,$73,$5f,$49,$6e,$70,$75,$74,$0a,$7b,
    $0a,$20,$20,$20,$20,$66,$6c,$6f,$61,$74,$34,$20,$70,$6f,$73,$69,
    $74,$69,$6f,$6e,$20,$3a,$20,$54,$45,$58,$43,$4f,$4f,$52,$44,$30,
    $3b,$0a,$20,$20,$20,$20,$66,$6c,$6f,$61,$74,$33,$20,$6e,$6f,$72,
    $6d,$61,$6c,$20,$3a,$20,$54,$45,$58,$43,$4f,$4f,$52,$44,$31,$3b,
    $0a,$7d,$3b,$0a,$0a,$73,$74,$72,$75,$63,$74,$20,$53,$50,$49,$52,
    $56,$5f,$43,$72,$6f,$73,$73,$5f,$4f,$75,$74,$70,$75,$74,$0a,$7b,
    $0a,$20,$20,$20,$20,$66,$6c,$6f,$61,$74,$34,$20,$67,$6c,$5f,$50,
    $6f,$73,$69,$74,$69,$6f,$6e,$20,$3a,$20,$53,$56,$5f,$50,$6f,$73,
    $69,$74,$69,$6f,$6e,$3b,$0a,$7d,$3b,$0a,$0a,$76,$6f,$69,$64,$20,
    $76,$65,$72,$74,$5f,$6d,$61,$69,$6e,$28,$29,$0a,$7b,$0a,$20,$20,
    $20,$20,$67,$6c,$5f,$50,$6f,$73,$69,$74,$69,$6f,$6e,$20,$3d,$20,
    $6d,$75,$6c,$28,$70,$6f,$73,$69,$74,$69,$6f,$6e,$2c,$20,$5f,$33,
    $34,$5f,$6d,$76,$70,$29,$3b,$0a,$7d,$0a,$0a,$53,$50,$49,$52,$56,
    $5f,$43,$72,$6f,$73,$73,$5f,$4f,$75,$74,$70,$75,$74,$20,$6d,$61,
    $69,$6e,$28,$53,$50,$49,$52,$56,$5f,$43,$72,$6f,$73,$73,$5f,$49,
    $6e,$70,$75,$74,$20,$73,$74,$61,$67,$65,$5f,$69,$6e,$70,$75,$74,
    $29,$0a,$7b,$0a,$20,$20,$20,$20,$70,$6f,$73,$69,$74,$69,$6f,$6e,
    $20,$3d,$20,$73,$74,$61,$67,$65,$5f,$69,$6e,$70,$75,$74,$2e,$70,
    $6f,$73,$69,$74,$69,$6f,$6e,$3b,$0a,$20,$20,$20,$20,$6e,$6f,$72,
    $6d,$61,$6c,$20,$3d,$20,$73,$74,$61,$67,$65,$5f,$69,$6e,$70,$75,
    $74,$2e,$6e,$6f,$72,$6d,$61,$6c,$3b,$0a,$20,$20,$20,$20,$76,$65,
    $72,$74,$5f,$6d,$61,$69,$6e,$28,$29,$3b,$0a,$20,$20,$20,$20,$53,
    $50,$49,$52,$56,$5f,$43,$72,$6f,$73,$73,$5f,$4f,$75,$74,$70,$75,
    $74,$20,$73,$74,$61,$67,$65,$5f,$6f,$75,$74,$70,$75,$74,$3b,$0a,
    $20,$20,$20,$20,$73,$74,$61,$67,$65,$5f,$6f,$75,$74,$70,$75,$74,
    $2e,$67,$6c,$5f,$50,$6f,$73,$69,$74,$69,$6f,$6e,$20,$3d,$20,$67,
    $6c,$5f,$50,$6f,$73,$69,$74,$69,$6f,$6e,$3b,$0a,$20,$20,$20,$20,
    $72,$65,$74,$75,$72,$6e,$20,$73,$74,$61,$67,$65,$5f,$6f,$75,$74,
    $70,$75,$74,$3b,$0a,$7d,$0a,$00);
{$ENDIF}

(*
  cbuffer phong_params : register(b1)
  {
      float3 _12_mat_diffuse : packoffset(c0);
      float3 _12_mat_specular : packoffset(c1);
      float _12_mat_spec_power : packoffset(c1.w);
  };


  static float4 frag_color;

  struct SPIRV_Cross_Output
  {
      float4 frag_color : SV_Target0;
  };

  void frag_main()
  {
      frag_color = float4(_12_mat_diffuse, 1.0f);
  }

  SPIRV_Cross_Output main()
  {
      frag_main();
      SPIRV_Cross_Output stage_output;
      stage_output.frag_color = frag_color;
      return stage_output;
  }
*)
{$IFDEF SOKOL_D3D11}
const
  MFS_SOURCE_HLSL5: array [0..499] of Byte = (
    $63,$62,$75,$66,$66,$65,$72,$20,$70,$68,$6f,$6e,$67,$5f,$70,$61,
    $72,$61,$6d,$73,$20,$3a,$20,$72,$65,$67,$69,$73,$74,$65,$72,$28,
    $62,$31,$29,$0a,$7b,$0a,$20,$20,$20,$20,$66,$6c,$6f,$61,$74,$33,
    $20,$5f,$31,$32,$5f,$6d,$61,$74,$5f,$64,$69,$66,$66,$75,$73,$65,
    $20,$3a,$20,$70,$61,$63,$6b,$6f,$66,$66,$73,$65,$74,$28,$63,$30,
    $29,$3b,$0a,$20,$20,$20,$20,$66,$6c,$6f,$61,$74,$33,$20,$5f,$31,
    $32,$5f,$6d,$61,$74,$5f,$73,$70,$65,$63,$75,$6c,$61,$72,$20,$3a,
    $20,$70,$61,$63,$6b,$6f,$66,$66,$73,$65,$74,$28,$63,$31,$29,$3b,
    $0a,$20,$20,$20,$20,$66,$6c,$6f,$61,$74,$20,$5f,$31,$32,$5f,$6d,
    $61,$74,$5f,$73,$70,$65,$63,$5f,$70,$6f,$77,$65,$72,$20,$3a,$20,
    $70,$61,$63,$6b,$6f,$66,$66,$73,$65,$74,$28,$63,$31,$2e,$77,$29,
    $3b,$0a,$7d,$3b,$0a,$0a,$0a,$73,$74,$61,$74,$69,$63,$20,$66,$6c,
    $6f,$61,$74,$34,$20,$66,$72,$61,$67,$5f,$63,$6f,$6c,$6f,$72,$3b,
    $0a,$0a,$73,$74,$72,$75,$63,$74,$20,$53,$50,$49,$52,$56,$5f,$43,
    $72,$6f,$73,$73,$5f,$4f,$75,$74,$70,$75,$74,$0a,$7b,$0a,$20,$20,
    $20,$20,$66,$6c,$6f,$61,$74,$34,$20,$66,$72,$61,$67,$5f,$63,$6f,
    $6c,$6f,$72,$20,$3a,$20,$53,$56,$5f,$54,$61,$72,$67,$65,$74,$30,
    $3b,$0a,$7d,$3b,$0a,$0a,$76,$6f,$69,$64,$20,$66,$72,$61,$67,$5f,
    $6d,$61,$69,$6e,$28,$29,$0a,$7b,$0a,$20,$20,$20,$20,$66,$72,$61,
    $67,$5f,$63,$6f,$6c,$6f,$72,$20,$3d,$20,$66,$6c,$6f,$61,$74,$34,
    $28,$5f,$31,$32,$5f,$6d,$61,$74,$5f,$64,$69,$66,$66,$75,$73,$65,
    $2c,$20,$31,$2e,$30,$66,$29,$3b,$0a,$7d,$0a,$0a,$53,$50,$49,$52,
    $56,$5f,$43,$72,$6f,$73,$73,$5f,$4f,$75,$74,$70,$75,$74,$20,$6d,
    $61,$69,$6e,$28,$29,$0a,$7b,$0a,$20,$20,$20,$20,$66,$72,$61,$67,
    $5f,$6d,$61,$69,$6e,$28,$29,$3b,$0a,$20,$20,$20,$20,$53,$50,$49,
    $52,$56,$5f,$43,$72,$6f,$73,$73,$5f,$4f,$75,$74,$70,$75,$74,$20,
    $73,$74,$61,$67,$65,$5f,$6f,$75,$74,$70,$75,$74,$3b,$0a,$20,$20,
    $20,$20,$73,$74,$61,$67,$65,$5f,$6f,$75,$74,$70,$75,$74,$2e,$66,
    $72,$61,$67,$5f,$63,$6f,$6c,$6f,$72,$20,$3d,$20,$66,$72,$61,$67,
    $5f,$63,$6f,$6c,$6f,$72,$3b,$0a,$20,$20,$20,$20,$72,$65,$74,$75,
    $72,$6e,$20,$73,$74,$61,$67,$65,$5f,$6f,$75,$74,$70,$75,$74,$3b,
    $0a,$7d,$0a,$00);
{$ENDIF}

(*
  #include <metal_stdlib>
  #include <simd/simd.h>

  using namespace metal;

  struct vs_params
  {
      float4x4 mvp;
      float4x4 model;
  };

  struct main0_out
  {
      float4 gl_Position [[position]];
  };

  struct main0_in
  {
      float4 position [[attribute(0)]];
  };

  vertex main0_out main0(main0_in in [[stage_in]], constant vs_params& _34 [[buffer(0)]])
  {
      main0_out out = {};
      out.gl_Position = _34.mvp * in.position;
      return out;
  }

*)
{$IFDEF SOKOL_METAL}
const
  MVS_SOURCE_METAL_MACOS: array [0..431] of Byte = (
    $23,$69,$6e,$63,$6c,$75,$64,$65,$20,$3c,$6d,$65,$74,$61,$6c,$5f,
    $73,$74,$64,$6c,$69,$62,$3e,$0a,$23,$69,$6e,$63,$6c,$75,$64,$65,
    $20,$3c,$73,$69,$6d,$64,$2f,$73,$69,$6d,$64,$2e,$68,$3e,$0a,$0a,
    $75,$73,$69,$6e,$67,$20,$6e,$61,$6d,$65,$73,$70,$61,$63,$65,$20,
    $6d,$65,$74,$61,$6c,$3b,$0a,$0a,$73,$74,$72,$75,$63,$74,$20,$76,
    $73,$5f,$70,$61,$72,$61,$6d,$73,$0a,$7b,$0a,$20,$20,$20,$20,$66,
    $6c,$6f,$61,$74,$34,$78,$34,$20,$6d,$76,$70,$3b,$0a,$20,$20,$20,
    $20,$66,$6c,$6f,$61,$74,$34,$78,$34,$20,$6d,$6f,$64,$65,$6c,$3b,
    $0a,$7d,$3b,$0a,$0a,$73,$74,$72,$75,$63,$74,$20,$6d,$61,$69,$6e,
    $30,$5f,$6f,$75,$74,$0a,$7b,$0a,$20,$20,$20,$20,$66,$6c,$6f,$61,
    $74,$34,$20,$67,$6c,$5f,$50,$6f,$73,$69,$74,$69,$6f,$6e,$20,$5b,
    $5b,$70,$6f,$73,$69,$74,$69,$6f,$6e,$5d,$5d,$3b,$0a,$7d,$3b,$0a,
    $0a,$73,$74,$72,$75,$63,$74,$20,$6d,$61,$69,$6e,$30,$5f,$69,$6e,
    $0a,$7b,$0a,$20,$20,$20,$20,$66,$6c,$6f,$61,$74,$34,$20,$70,$6f,
    $73,$69,$74,$69,$6f,$6e,$20,$5b,$5b,$61,$74,$74,$72,$69,$62,$75,
    $74,$65,$28,$30,$29,$5d,$5d,$3b,$0a,$7d,$3b,$0a,$0a,$76,$65,$72,
    $74,$65,$78,$20,$6d,$61,$69,$6e,$30,$5f,$6f,$75,$74,$20,$6d,$61,
    $69,$6e,$30,$28,$6d,$61,$69,$6e,$30,$5f,$69,$6e,$20,$69,$6e,$20,
    $5b,$5b,$73,$74,$61,$67,$65,$5f,$69,$6e,$5d,$5d,$2c,$20,$63,$6f,
    $6e,$73,$74,$61,$6e,$74,$20,$76,$73,$5f,$70,$61,$72,$61,$6d,$73,
    $26,$20,$5f,$33,$34,$20,$5b,$5b,$62,$75,$66,$66,$65,$72,$28,$30,
    $29,$5d,$5d,$29,$0a,$7b,$0a,$20,$20,$20,$20,$6d,$61,$69,$6e,$30,
    $5f,$6f,$75,$74,$20,$6f,$75,$74,$20,$3d,$20,$7b,$7d,$3b,$0a,$20,
    $20,$20,$20,$6f,$75,$74,$2e,$67,$6c,$5f,$50,$6f,$73,$69,$74,$69,
    $6f,$6e,$20,$3d,$20,$5f,$33,$34,$2e,$6d,$76,$70,$20,$2a,$20,$69,
    $6e,$2e,$70,$6f,$73,$69,$74,$69,$6f,$6e,$3b,$0a,$20,$20,$20,$20,
    $72,$65,$74,$75,$72,$6e,$20,$6f,$75,$74,$3b,$0a,$7d,$0a,$0a,$00);
{$ENDIF}

(*
  #include <metal_stdlib>
  #include <simd/simd.h>

  using namespace metal;

  struct phong_params
  {
      float3 mat_diffuse;
      packed_float3 mat_specular;
      float mat_spec_power;
  };

  struct main0_out
  {
      float4 frag_color [[color(0)]];
  };

  fragment main0_out main0(constant phong_params& _12 [[buffer(1)]])
  {
      main0_out out = {};
      out.frag_color = float4(_12.mat_diffuse, 1.0);
      return out;
  }

*)
{$IFDEF SOKOL_METAL}
const
  MFS_SOURCE_METAL_MACOS: array [0..402] of Byte = (
    $23,$69,$6e,$63,$6c,$75,$64,$65,$20,$3c,$6d,$65,$74,$61,$6c,$5f,
    $73,$74,$64,$6c,$69,$62,$3e,$0a,$23,$69,$6e,$63,$6c,$75,$64,$65,
    $20,$3c,$73,$69,$6d,$64,$2f,$73,$69,$6d,$64,$2e,$68,$3e,$0a,$0a,
    $75,$73,$69,$6e,$67,$20,$6e,$61,$6d,$65,$73,$70,$61,$63,$65,$20,
    $6d,$65,$74,$61,$6c,$3b,$0a,$0a,$73,$74,$72,$75,$63,$74,$20,$70,
    $68,$6f,$6e,$67,$5f,$70,$61,$72,$61,$6d,$73,$0a,$7b,$0a,$20,$20,
    $20,$20,$66,$6c,$6f,$61,$74,$33,$20,$6d,$61,$74,$5f,$64,$69,$66,
    $66,$75,$73,$65,$3b,$0a,$20,$20,$20,$20,$70,$61,$63,$6b,$65,$64,
    $5f,$66,$6c,$6f,$61,$74,$33,$20,$6d,$61,$74,$5f,$73,$70,$65,$63,
    $75,$6c,$61,$72,$3b,$0a,$20,$20,$20,$20,$66,$6c,$6f,$61,$74,$20,
    $6d,$61,$74,$5f,$73,$70,$65,$63,$5f,$70,$6f,$77,$65,$72,$3b,$0a,
    $7d,$3b,$0a,$0a,$73,$74,$72,$75,$63,$74,$20,$6d,$61,$69,$6e,$30,
    $5f,$6f,$75,$74,$0a,$7b,$0a,$20,$20,$20,$20,$66,$6c,$6f,$61,$74,
    $34,$20,$66,$72,$61,$67,$5f,$63,$6f,$6c,$6f,$72,$20,$5b,$5b,$63,
    $6f,$6c,$6f,$72,$28,$30,$29,$5d,$5d,$3b,$0a,$7d,$3b,$0a,$0a,$66,
    $72,$61,$67,$6d,$65,$6e,$74,$20,$6d,$61,$69,$6e,$30,$5f,$6f,$75,
    $74,$20,$6d,$61,$69,$6e,$30,$28,$63,$6f,$6e,$73,$74,$61,$6e,$74,
    $20,$70,$68,$6f,$6e,$67,$5f,$70,$61,$72,$61,$6d,$73,$26,$20,$5f,
    $31,$32,$20,$5b,$5b,$62,$75,$66,$66,$65,$72,$28,$31,$29,$5d,$5d,
    $29,$0a,$7b,$0a,$20,$20,$20,$20,$6d,$61,$69,$6e,$30,$5f,$6f,$75,
    $74,$20,$6f,$75,$74,$20,$3d,$20,$7b,$7d,$3b,$0a,$20,$20,$20,$20,
    $6f,$75,$74,$2e,$66,$72,$61,$67,$5f,$63,$6f,$6c,$6f,$72,$20,$3d,
    $20,$66,$6c,$6f,$61,$74,$34,$28,$5f,$31,$32,$2e,$6d,$61,$74,$5f,
    $64,$69,$66,$66,$75,$73,$65,$2c,$20,$31,$2e,$30,$29,$3b,$0a,$20,
    $20,$20,$20,$72,$65,$74,$75,$72,$6e,$20,$6f,$75,$74,$3b,$0a,$7d,
    $0a,$0a,$00);
{$ENDIF}

(*
  #include <metal_stdlib>
  #include <simd/simd.h>

  using namespace metal;

  struct vs_params
  {
      float4x4 mvp;
      float4x4 model;
  };

  struct main0_out
  {
      float4 gl_Position [[position]];
  };

  struct main0_in
  {
      float4 position [[attribute(0)]];
  };

  vertex main0_out main0(main0_in in [[stage_in]], constant vs_params& _34 [[buffer(0)]])
  {
      main0_out out = {};
      out.gl_Position = _34.mvp * in.position;
      return out;
  }

*)
{$IFDEF SOKOL_METAL}
const
  MVS_SOURCE_METAL_IOS: array [0..431] of Byte = (
    $23,$69,$6e,$63,$6c,$75,$64,$65,$20,$3c,$6d,$65,$74,$61,$6c,$5f,
    $73,$74,$64,$6c,$69,$62,$3e,$0a,$23,$69,$6e,$63,$6c,$75,$64,$65,
    $20,$3c,$73,$69,$6d,$64,$2f,$73,$69,$6d,$64,$2e,$68,$3e,$0a,$0a,
    $75,$73,$69,$6e,$67,$20,$6e,$61,$6d,$65,$73,$70,$61,$63,$65,$20,
    $6d,$65,$74,$61,$6c,$3b,$0a,$0a,$73,$74,$72,$75,$63,$74,$20,$76,
    $73,$5f,$70,$61,$72,$61,$6d,$73,$0a,$7b,$0a,$20,$20,$20,$20,$66,
    $6c,$6f,$61,$74,$34,$78,$34,$20,$6d,$76,$70,$3b,$0a,$20,$20,$20,
    $20,$66,$6c,$6f,$61,$74,$34,$78,$34,$20,$6d,$6f,$64,$65,$6c,$3b,
    $0a,$7d,$3b,$0a,$0a,$73,$74,$72,$75,$63,$74,$20,$6d,$61,$69,$6e,
    $30,$5f,$6f,$75,$74,$0a,$7b,$0a,$20,$20,$20,$20,$66,$6c,$6f,$61,
    $74,$34,$20,$67,$6c,$5f,$50,$6f,$73,$69,$74,$69,$6f,$6e,$20,$5b,
    $5b,$70,$6f,$73,$69,$74,$69,$6f,$6e,$5d,$5d,$3b,$0a,$7d,$3b,$0a,
    $0a,$73,$74,$72,$75,$63,$74,$20,$6d,$61,$69,$6e,$30,$5f,$69,$6e,
    $0a,$7b,$0a,$20,$20,$20,$20,$66,$6c,$6f,$61,$74,$34,$20,$70,$6f,
    $73,$69,$74,$69,$6f,$6e,$20,$5b,$5b,$61,$74,$74,$72,$69,$62,$75,
    $74,$65,$28,$30,$29,$5d,$5d,$3b,$0a,$7d,$3b,$0a,$0a,$76,$65,$72,
    $74,$65,$78,$20,$6d,$61,$69,$6e,$30,$5f,$6f,$75,$74,$20,$6d,$61,
    $69,$6e,$30,$28,$6d,$61,$69,$6e,$30,$5f,$69,$6e,$20,$69,$6e,$20,
    $5b,$5b,$73,$74,$61,$67,$65,$5f,$69,$6e,$5d,$5d,$2c,$20,$63,$6f,
    $6e,$73,$74,$61,$6e,$74,$20,$76,$73,$5f,$70,$61,$72,$61,$6d,$73,
    $26,$20,$5f,$33,$34,$20,$5b,$5b,$62,$75,$66,$66,$65,$72,$28,$30,
    $29,$5d,$5d,$29,$0a,$7b,$0a,$20,$20,$20,$20,$6d,$61,$69,$6e,$30,
    $5f,$6f,$75,$74,$20,$6f,$75,$74,$20,$3d,$20,$7b,$7d,$3b,$0a,$20,
    $20,$20,$20,$6f,$75,$74,$2e,$67,$6c,$5f,$50,$6f,$73,$69,$74,$69,
    $6f,$6e,$20,$3d,$20,$5f,$33,$34,$2e,$6d,$76,$70,$20,$2a,$20,$69,
    $6e,$2e,$70,$6f,$73,$69,$74,$69,$6f,$6e,$3b,$0a,$20,$20,$20,$20,
    $72,$65,$74,$75,$72,$6e,$20,$6f,$75,$74,$3b,$0a,$7d,$0a,$0a,$00);
{$ENDIF}

(*
  #include <metal_stdlib>
  #include <simd/simd.h>

  using namespace metal;

  struct phong_params
  {
      float3 mat_diffuse;
      packed_float3 mat_specular;
      float mat_spec_power;
  };

  struct main0_out
  {
      float4 frag_color [[color(0)]];
  };

  fragment main0_out main0(constant phong_params& _12 [[buffer(1)]])
  {
      main0_out out = {};
      out.frag_color = float4(_12.mat_diffuse, 1.0);
      return out;
  }

*)
{$IFDEF SOKOL_METAL}
const
  MFS_SOURCE_METAL_IOS: array [0..402] of Byte = (
    $23,$69,$6e,$63,$6c,$75,$64,$65,$20,$3c,$6d,$65,$74,$61,$6c,$5f,
    $73,$74,$64,$6c,$69,$62,$3e,$0a,$23,$69,$6e,$63,$6c,$75,$64,$65,
    $20,$3c,$73,$69,$6d,$64,$2f,$73,$69,$6d,$64,$2e,$68,$3e,$0a,$0a,
    $75,$73,$69,$6e,$67,$20,$6e,$61,$6d,$65,$73,$70,$61,$63,$65,$20,
    $6d,$65,$74,$61,$6c,$3b,$0a,$0a,$73,$74,$72,$75,$63,$74,$20,$70,
    $68,$6f,$6e,$67,$5f,$70,$61,$72,$61,$6d,$73,$0a,$7b,$0a,$20,$20,
    $20,$20,$66,$6c,$6f,$61,$74,$33,$20,$6d,$61,$74,$5f,$64,$69,$66,
    $66,$75,$73,$65,$3b,$0a,$20,$20,$20,$20,$70,$61,$63,$6b,$65,$64,
    $5f,$66,$6c,$6f,$61,$74,$33,$20,$6d,$61,$74,$5f,$73,$70,$65,$63,
    $75,$6c,$61,$72,$3b,$0a,$20,$20,$20,$20,$66,$6c,$6f,$61,$74,$20,
    $6d,$61,$74,$5f,$73,$70,$65,$63,$5f,$70,$6f,$77,$65,$72,$3b,$0a,
    $7d,$3b,$0a,$0a,$73,$74,$72,$75,$63,$74,$20,$6d,$61,$69,$6e,$30,
    $5f,$6f,$75,$74,$0a,$7b,$0a,$20,$20,$20,$20,$66,$6c,$6f,$61,$74,
    $34,$20,$66,$72,$61,$67,$5f,$63,$6f,$6c,$6f,$72,$20,$5b,$5b,$63,
    $6f,$6c,$6f,$72,$28,$30,$29,$5d,$5d,$3b,$0a,$7d,$3b,$0a,$0a,$66,
    $72,$61,$67,$6d,$65,$6e,$74,$20,$6d,$61,$69,$6e,$30,$5f,$6f,$75,
    $74,$20,$6d,$61,$69,$6e,$30,$28,$63,$6f,$6e,$73,$74,$61,$6e,$74,
    $20,$70,$68,$6f,$6e,$67,$5f,$70,$61,$72,$61,$6d,$73,$26,$20,$5f,
    $31,$32,$20,$5b,$5b,$62,$75,$66,$66,$65,$72,$28,$31,$29,$5d,$5d,
    $29,$0a,$7b,$0a,$20,$20,$20,$20,$6d,$61,$69,$6e,$30,$5f,$6f,$75,
    $74,$20,$6f,$75,$74,$20,$3d,$20,$7b,$7d,$3b,$0a,$20,$20,$20,$20,
    $6f,$75,$74,$2e,$66,$72,$61,$67,$5f,$63,$6f,$6c,$6f,$72,$20,$3d,
    $20,$66,$6c,$6f,$61,$74,$34,$28,$5f,$31,$32,$2e,$6d,$61,$74,$5f,
    $64,$69,$66,$66,$75,$73,$65,$2c,$20,$31,$2e,$30,$29,$3b,$0a,$20,
    $20,$20,$20,$72,$65,$74,$75,$72,$6e,$20,$6f,$75,$74,$3b,$0a,$7d,
    $0a,$0a,$00);
{$ENDIF}

(*
  #version 460

  layout(set = 0, binding = 0, std140) uniform vs_params
  {
      mat4 mvp;
      mat4 model;
  } _34;

  layout(location = 0) in vec4 position;
  layout(location = 1) in vec3 normal;

  void main()
  {
      gl_Position = _34.mvp * position;
  }

*)
{$IFDEF SOKOL_VULKAN}
const
  MVS_BYTECODE_SPIRV_VK: array [0..1155] of Byte = (
    $03,$02,$23,$07,$00,$04,$01,$00,$0b,$00,$08,$00,$20,$00,$00,$00,
    $00,$00,$00,$00,$11,$00,$02,$00,$01,$00,$00,$00,$0b,$00,$06,$00,
    $01,$00,$00,$00,$47,$4c,$53,$4c,$2e,$73,$74,$64,$2e,$34,$35,$30,
    $00,$00,$00,$00,$0e,$00,$03,$00,$00,$00,$00,$00,$01,$00,$00,$00,
    $0f,$00,$09,$00,$00,$00,$00,$00,$04,$00,$00,$00,$6d,$61,$69,$6e,
    $00,$00,$00,$00,$0d,$00,$00,$00,$13,$00,$00,$00,$18,$00,$00,$00,
    $1f,$00,$00,$00,$03,$00,$03,$00,$02,$00,$00,$00,$cc,$01,$00,$00,
    $05,$00,$04,$00,$04,$00,$00,$00,$6d,$61,$69,$6e,$00,$00,$00,$00,
    $05,$00,$06,$00,$0b,$00,$00,$00,$67,$6c,$5f,$50,$65,$72,$56,$65,
    $72,$74,$65,$78,$00,$00,$00,$00,$06,$00,$06,$00,$0b,$00,$00,$00,
    $00,$00,$00,$00,$67,$6c,$5f,$50,$6f,$73,$69,$74,$69,$6f,$6e,$00,
    $06,$00,$07,$00,$0b,$00,$00,$00,$01,$00,$00,$00,$67,$6c,$5f,$50,
    $6f,$69,$6e,$74,$53,$69,$7a,$65,$00,$00,$00,$00,$06,$00,$07,$00,
    $0b,$00,$00,$00,$02,$00,$00,$00,$67,$6c,$5f,$43,$6c,$69,$70,$44,
    $69,$73,$74,$61,$6e,$63,$65,$00,$06,$00,$07,$00,$0b,$00,$00,$00,
    $03,$00,$00,$00,$67,$6c,$5f,$43,$75,$6c,$6c,$44,$69,$73,$74,$61,
    $6e,$63,$65,$00,$05,$00,$03,$00,$0d,$00,$00,$00,$00,$00,$00,$00,
    $05,$00,$05,$00,$11,$00,$00,$00,$76,$73,$5f,$70,$61,$72,$61,$6d,
    $73,$00,$00,$00,$06,$00,$04,$00,$11,$00,$00,$00,$00,$00,$00,$00,
    $6d,$76,$70,$00,$06,$00,$05,$00,$11,$00,$00,$00,$01,$00,$00,$00,
    $6d,$6f,$64,$65,$6c,$00,$00,$00,$05,$00,$03,$00,$13,$00,$00,$00,
    $5f,$33,$34,$00,$05,$00,$05,$00,$18,$00,$00,$00,$70,$6f,$73,$69,
    $74,$69,$6f,$6e,$00,$00,$00,$00,$05,$00,$04,$00,$1f,$00,$00,$00,
    $6e,$6f,$72,$6d,$61,$6c,$00,$00,$47,$00,$03,$00,$0b,$00,$00,$00,
    $02,$00,$00,$00,$48,$00,$05,$00,$0b,$00,$00,$00,$00,$00,$00,$00,
    $0b,$00,$00,$00,$00,$00,$00,$00,$48,$00,$05,$00,$0b,$00,$00,$00,
    $01,$00,$00,$00,$0b,$00,$00,$00,$01,$00,$00,$00,$48,$00,$05,$00,
    $0b,$00,$00,$00,$02,$00,$00,$00,$0b,$00,$00,$00,$03,$00,$00,$00,
    $48,$00,$05,$00,$0b,$00,$00,$00,$03,$00,$00,$00,$0b,$00,$00,$00,
    $04,$00,$00,$00,$47,$00,$03,$00,$11,$00,$00,$00,$02,$00,$00,$00,
    $48,$00,$04,$00,$11,$00,$00,$00,$00,$00,$00,$00,$05,$00,$00,$00,
    $48,$00,$05,$00,$11,$00,$00,$00,$00,$00,$00,$00,$07,$00,$00,$00,
    $10,$00,$00,$00,$48,$00,$05,$00,$11,$00,$00,$00,$00,$00,$00,$00,
    $23,$00,$00,$00,$00,$00,$00,$00,$48,$00,$04,$00,$11,$00,$00,$00,
    $01,$00,$00,$00,$05,$00,$00,$00,$48,$00,$05,$00,$11,$00,$00,$00,
    $01,$00,$00,$00,$07,$00,$00,$00,$10,$00,$00,$00,$48,$00,$05,$00,
    $11,$00,$00,$00,$01,$00,$00,$00,$23,$00,$00,$00,$40,$00,$00,$00,
    $47,$00,$04,$00,$13,$00,$00,$00,$21,$00,$00,$00,$00,$00,$00,$00,
    $47,$00,$04,$00,$13,$00,$00,$00,$22,$00,$00,$00,$00,$00,$00,$00,
    $47,$00,$04,$00,$18,$00,$00,$00,$1e,$00,$00,$00,$00,$00,$00,$00,
    $47,$00,$04,$00,$1f,$00,$00,$00,$1e,$00,$00,$00,$01,$00,$00,$00,
    $13,$00,$02,$00,$02,$00,$00,$00,$21,$00,$03,$00,$03,$00,$00,$00,
    $02,$00,$00,$00,$16,$00,$03,$00,$06,$00,$00,$00,$20,$00,$00,$00,
    $17,$00,$04,$00,$07,$00,$00,$00,$06,$00,$00,$00,$04,$00,$00,$00,
    $15,$00,$04,$00,$08,$00,$00,$00,$20,$00,$00,$00,$00,$00,$00,$00,
    $2b,$00,$04,$00,$08,$00,$00,$00,$09,$00,$00,$00,$01,$00,$00,$00,
    $1c,$00,$04,$00,$0a,$00,$00,$00,$06,$00,$00,$00,$09,$00,$00,$00,
    $1e,$00,$06,$00,$0b,$00,$00,$00,$07,$00,$00,$00,$06,$00,$00,$00,
    $0a,$00,$00,$00,$0a,$00,$00,$00,$20,$00,$04,$00,$0c,$00,$00,$00,
    $03,$00,$00,$00,$0b,$00,$00,$00,$3b,$00,$04,$00,$0c,$00,$00,$00,
    $0d,$00,$00,$00,$03,$00,$00,$00,$15,$00,$04,$00,$0e,$00,$00,$00,
    $20,$00,$00,$00,$01,$00,$00,$00,$2b,$00,$04,$00,$0e,$00,$00,$00,
    $0f,$00,$00,$00,$00,$00,$00,$00,$18,$00,$04,$00,$10,$00,$00,$00,
    $07,$00,$00,$00,$04,$00,$00,$00,$1e,$00,$04,$00,$11,$00,$00,$00,
    $10,$00,$00,$00,$10,$00,$00,$00,$20,$00,$04,$00,$12,$00,$00,$00,
    $02,$00,$00,$00,$11,$00,$00,$00,$3b,$00,$04,$00,$12,$00,$00,$00,
    $13,$00,$00,$00,$02,$00,$00,$00,$20,$00,$04,$00,$14,$00,$00,$00,
    $02,$00,$00,$00,$10,$00,$00,$00,$20,$00,$04,$00,$17,$00,$00,$00,
    $01,$00,$00,$00,$07,$00,$00,$00,$3b,$00,$04,$00,$17,$00,$00,$00,
    $18,$00,$00,$00,$01,$00,$00,$00,$20,$00,$04,$00,$1b,$00,$00,$00,
    $03,$00,$00,$00,$07,$00,$00,$00,$17,$00,$04,$00,$1d,$00,$00,$00,
    $06,$00,$00,$00,$03,$00,$00,$00,$20,$00,$04,$00,$1e,$00,$00,$00,
    $01,$00,$00,$00,$1d,$00,$00,$00,$3b,$00,$04,$00,$1e,$00,$00,$00,
    $1f,$00,$00,$00,$01,$00,$00,$00,$36,$00,$05,$00,$02,$00,$00,$00,
    $04,$00,$00,$00,$00,$00,$00,$00,$03,$00,$00,$00,$f8,$00,$02,$00,
    $05,$00,$00,$00,$41,$00,$05,$00,$14,$00,$00,$00,$15,$00,$00,$00,
    $13,$00,$00,$00,$0f,$00,$00,$00,$3d,$00,$04,$00,$10,$00,$00,$00,
    $16,$00,$00,$00,$15,$00,$00,$00,$3d,$00,$04,$00,$07,$00,$00,$00,
    $19,$00,$00,$00,$18,$00,$00,$00,$91,$00,$05,$00,$07,$00,$00,$00,
    $1a,$00,$00,$00,$16,$00,$00,$00,$19,$00,$00,$00,$41,$00,$05,$00,
    $1b,$00,$00,$00,$1c,$00,$00,$00,$0d,$00,$00,$00,$0f,$00,$00,$00,
    $3e,$00,$03,$00,$1c,$00,$00,$00,$1a,$00,$00,$00,$fd,$00,$01,$00,
    $38,$00,$01,$00);
{$ENDIF}

(*
  #version 460

  layout(set = 0, binding = 1, std140) uniform phong_params
  {
      vec3 mat_diffuse;
      vec3 mat_specular;
      float mat_spec_power;
  } _12;

  layout(location = 0) out vec4 frag_color;

  void main()
  {
      frag_color = vec4(_12.mat_diffuse, 1.0);
  }

*)
{$IFDEF SOKOL_VULKAN}
const
  MFS_BYTECODE_SPIRV_VK: array [0..771] of Byte = (
    $03,$02,$23,$07,$00,$04,$01,$00,$0b,$00,$08,$00,$18,$00,$00,$00,
    $00,$00,$00,$00,$11,$00,$02,$00,$01,$00,$00,$00,$0b,$00,$06,$00,
    $01,$00,$00,$00,$47,$4c,$53,$4c,$2e,$73,$74,$64,$2e,$34,$35,$30,
    $00,$00,$00,$00,$0e,$00,$03,$00,$00,$00,$00,$00,$01,$00,$00,$00,
    $0f,$00,$07,$00,$04,$00,$00,$00,$04,$00,$00,$00,$6d,$61,$69,$6e,
    $00,$00,$00,$00,$09,$00,$00,$00,$0d,$00,$00,$00,$10,$00,$03,$00,
    $04,$00,$00,$00,$07,$00,$00,$00,$03,$00,$03,$00,$02,$00,$00,$00,
    $cc,$01,$00,$00,$05,$00,$04,$00,$04,$00,$00,$00,$6d,$61,$69,$6e,
    $00,$00,$00,$00,$05,$00,$05,$00,$09,$00,$00,$00,$66,$72,$61,$67,
    $5f,$63,$6f,$6c,$6f,$72,$00,$00,$05,$00,$06,$00,$0b,$00,$00,$00,
    $70,$68,$6f,$6e,$67,$5f,$70,$61,$72,$61,$6d,$73,$00,$00,$00,$00,
    $06,$00,$06,$00,$0b,$00,$00,$00,$00,$00,$00,$00,$6d,$61,$74,$5f,
    $64,$69,$66,$66,$75,$73,$65,$00,$06,$00,$07,$00,$0b,$00,$00,$00,
    $01,$00,$00,$00,$6d,$61,$74,$5f,$73,$70,$65,$63,$75,$6c,$61,$72,
    $00,$00,$00,$00,$06,$00,$07,$00,$0b,$00,$00,$00,$02,$00,$00,$00,
    $6d,$61,$74,$5f,$73,$70,$65,$63,$5f,$70,$6f,$77,$65,$72,$00,$00,
    $05,$00,$03,$00,$0d,$00,$00,$00,$5f,$31,$32,$00,$47,$00,$04,$00,
    $09,$00,$00,$00,$1e,$00,$00,$00,$00,$00,$00,$00,$47,$00,$03,$00,
    $0b,$00,$00,$00,$02,$00,$00,$00,$48,$00,$05,$00,$0b,$00,$00,$00,
    $00,$00,$00,$00,$23,$00,$00,$00,$00,$00,$00,$00,$48,$00,$05,$00,
    $0b,$00,$00,$00,$01,$00,$00,$00,$23,$00,$00,$00,$10,$00,$00,$00,
    $48,$00,$05,$00,$0b,$00,$00,$00,$02,$00,$00,$00,$23,$00,$00,$00,
    $1c,$00,$00,$00,$47,$00,$04,$00,$0d,$00,$00,$00,$21,$00,$00,$00,
    $01,$00,$00,$00,$47,$00,$04,$00,$0d,$00,$00,$00,$22,$00,$00,$00,
    $00,$00,$00,$00,$13,$00,$02,$00,$02,$00,$00,$00,$21,$00,$03,$00,
    $03,$00,$00,$00,$02,$00,$00,$00,$16,$00,$03,$00,$06,$00,$00,$00,
    $20,$00,$00,$00,$17,$00,$04,$00,$07,$00,$00,$00,$06,$00,$00,$00,
    $04,$00,$00,$00,$20,$00,$04,$00,$08,$00,$00,$00,$03,$00,$00,$00,
    $07,$00,$00,$00,$3b,$00,$04,$00,$08,$00,$00,$00,$09,$00,$00,$00,
    $03,$00,$00,$00,$17,$00,$04,$00,$0a,$00,$00,$00,$06,$00,$00,$00,
    $03,$00,$00,$00,$1e,$00,$05,$00,$0b,$00,$00,$00,$0a,$00,$00,$00,
    $0a,$00,$00,$00,$06,$00,$00,$00,$20,$00,$04,$00,$0c,$00,$00,$00,
    $02,$00,$00,$00,$0b,$00,$00,$00,$3b,$00,$04,$00,$0c,$00,$00,$00,
    $0d,$00,$00,$00,$02,$00,$00,$00,$15,$00,$04,$00,$0e,$00,$00,$00,
    $20,$00,$00,$00,$01,$00,$00,$00,$2b,$00,$04,$00,$0e,$00,$00,$00,
    $0f,$00,$00,$00,$00,$00,$00,$00,$20,$00,$04,$00,$10,$00,$00,$00,
    $02,$00,$00,$00,$0a,$00,$00,$00,$2b,$00,$04,$00,$06,$00,$00,$00,
    $13,$00,$00,$00,$00,$00,$80,$3f,$36,$00,$05,$00,$02,$00,$00,$00,
    $04,$00,$00,$00,$00,$00,$00,$00,$03,$00,$00,$00,$f8,$00,$02,$00,
    $05,$00,$00,$00,$41,$00,$05,$00,$10,$00,$00,$00,$11,$00,$00,$00,
    $0d,$00,$00,$00,$0f,$00,$00,$00,$3d,$00,$04,$00,$0a,$00,$00,$00,
    $12,$00,$00,$00,$11,$00,$00,$00,$51,$00,$05,$00,$06,$00,$00,$00,
    $14,$00,$00,$00,$12,$00,$00,$00,$00,$00,$00,$00,$51,$00,$05,$00,
    $06,$00,$00,$00,$15,$00,$00,$00,$12,$00,$00,$00,$01,$00,$00,$00,
    $51,$00,$05,$00,$06,$00,$00,$00,$16,$00,$00,$00,$12,$00,$00,$00,
    $02,$00,$00,$00,$50,$00,$07,$00,$07,$00,$00,$00,$17,$00,$00,$00,
    $14,$00,$00,$00,$15,$00,$00,$00,$16,$00,$00,$00,$13,$00,$00,$00,
    $3e,$00,$03,$00,$09,$00,$00,$00,$17,$00,$00,$00,$fd,$00,$01,$00,
    $38,$00,$01,$00);
{$ENDIF}

var
  GProgShaderDesc: TNativeShaderDesc;

procedure InitProgShaderDesc;
begin
  GProgShaderDesc.Init;
  
  {$IFDEF SOKOL_GLCORE}
  if (TGfx.Backend = TBackend.GLCore) then
  begin
    GProgShaderDesc.vertex_func.source := @MVS_SOURCE_GLSL410;
    GProgShaderDesc.vertex_func.entry := 'main';
    GProgShaderDesc.fragment_func.source := @MFS_SOURCE_GLSL410;
    GProgShaderDesc.fragment_func.entry := 'main';
    GProgShaderDesc.attrs[0].base_type := _SG_SHADERATTRBASETYPE_FLOAT;
    GProgShaderDesc.attrs[0].glsl_name := 'position';
    GProgShaderDesc.attrs[1].base_type := _SG_SHADERATTRBASETYPE_FLOAT;
    GProgShaderDesc.attrs[1].glsl_name := 'normal';
    GProgShaderDesc.uniform_blocks[0].stage := _SG_SHADERSTAGE_VERTEX;
    GProgShaderDesc.uniform_blocks[0].layout := _SG_UNIFORMLAYOUT_STD140;
    GProgShaderDesc.uniform_blocks[0].size := 128;
    GProgShaderDesc.uniform_blocks[0].glsl_uniforms[0].&type := _SG_UNIFORMTYPE_FLOAT4;
    GProgShaderDesc.uniform_blocks[0].glsl_uniforms[0].array_count := 8;
    GProgShaderDesc.uniform_blocks[0].glsl_uniforms[0].glsl_name := 'vs_params';
    GProgShaderDesc.uniform_blocks[1].stage := _SG_SHADERSTAGE_FRAGMENT;
    GProgShaderDesc.uniform_blocks[1].layout := _SG_UNIFORMLAYOUT_STD140;
    GProgShaderDesc.uniform_blocks[1].size := 32;
    GProgShaderDesc.uniform_blocks[1].glsl_uniforms[0].&type := _SG_UNIFORMTYPE_FLOAT4;
    GProgShaderDesc.uniform_blocks[1].glsl_uniforms[0].array_count := 2;
    GProgShaderDesc.uniform_blocks[1].glsl_uniforms[0].glsl_name := 'phong_params';
    GProgShaderDesc.&label := 'Mprog_shader';
  end;
  {$ENDIF !SOKOL_GLCORE}
  
  {$IFDEF SOKOL_GLES3}
  if (TGfx.Backend = TBackend.Gles3) then
  begin
    GProgShaderDesc.vertex_func.source := @MVS_SOURCE_GLSL300ES;
    GProgShaderDesc.vertex_func.entry := 'main';
    GProgShaderDesc.fragment_func.source := @MFS_SOURCE_GLSL300ES;
    GProgShaderDesc.fragment_func.entry := 'main';
    GProgShaderDesc.attrs[0].base_type := _SG_SHADERATTRBASETYPE_FLOAT;
    GProgShaderDesc.attrs[0].glsl_name := 'position';
    GProgShaderDesc.attrs[1].base_type := _SG_SHADERATTRBASETYPE_FLOAT;
    GProgShaderDesc.attrs[1].glsl_name := 'normal';
    GProgShaderDesc.uniform_blocks[0].stage := _SG_SHADERSTAGE_VERTEX;
    GProgShaderDesc.uniform_blocks[0].layout := _SG_UNIFORMLAYOUT_STD140;
    GProgShaderDesc.uniform_blocks[0].size := 128;
    GProgShaderDesc.uniform_blocks[0].glsl_uniforms[0].&type := _SG_UNIFORMTYPE_FLOAT4;
    GProgShaderDesc.uniform_blocks[0].glsl_uniforms[0].array_count := 8;
    GProgShaderDesc.uniform_blocks[0].glsl_uniforms[0].glsl_name := 'vs_params';
    GProgShaderDesc.uniform_blocks[1].stage := _SG_SHADERSTAGE_FRAGMENT;
    GProgShaderDesc.uniform_blocks[1].layout := _SG_UNIFORMLAYOUT_STD140;
    GProgShaderDesc.uniform_blocks[1].size := 32;
    GProgShaderDesc.uniform_blocks[1].glsl_uniforms[0].&type := _SG_UNIFORMTYPE_FLOAT4;
    GProgShaderDesc.uniform_blocks[1].glsl_uniforms[0].array_count := 2;
    GProgShaderDesc.uniform_blocks[1].glsl_uniforms[0].glsl_name := 'phong_params';
    GProgShaderDesc.&label := 'Mprog_shader';
  end;
  {$ENDIF !SOKOL_GLES3}
  
  {$IFDEF SOKOL_D3D11}
  if (TGfx.Backend = TBackend.D3D11) then
  begin
    GProgShaderDesc.vertex_func.source := @MVS_SOURCE_HLSL5;
    GProgShaderDesc.vertex_func.d3d11_target := 'vs_5_0';
    GProgShaderDesc.vertex_func.entry := 'main';
    GProgShaderDesc.fragment_func.source := @MFS_SOURCE_HLSL5;
    GProgShaderDesc.fragment_func.d3d11_target := 'ps_5_0';
    GProgShaderDesc.fragment_func.entry := 'main';
    GProgShaderDesc.attrs[0].base_type := _SG_SHADERATTRBASETYPE_FLOAT;
    GProgShaderDesc.attrs[0].hlsl_sem_name := 'TEXCOORD';
    GProgShaderDesc.attrs[0].hlsl_sem_index := 0;
    GProgShaderDesc.attrs[1].base_type := _SG_SHADERATTRBASETYPE_FLOAT;
    GProgShaderDesc.attrs[1].hlsl_sem_name := 'TEXCOORD';
    GProgShaderDesc.attrs[1].hlsl_sem_index := 1;
    GProgShaderDesc.uniform_blocks[0].stage := _SG_SHADERSTAGE_VERTEX;
    GProgShaderDesc.uniform_blocks[0].layout := _SG_UNIFORMLAYOUT_STD140;
    GProgShaderDesc.uniform_blocks[0].size := 128;
    GProgShaderDesc.uniform_blocks[0].hlsl_register_b_n := 0;
    GProgShaderDesc.uniform_blocks[1].stage := _SG_SHADERSTAGE_FRAGMENT;
    GProgShaderDesc.uniform_blocks[1].layout := _SG_UNIFORMLAYOUT_STD140;
    GProgShaderDesc.uniform_blocks[1].size := 32;
    GProgShaderDesc.uniform_blocks[1].hlsl_register_b_n := 1;
    GProgShaderDesc.&label := 'Mprog_shader';
  end;
  {$ENDIF !SOKOL_D3D11}
  
  {$IFDEF SOKOL_METAL}
  if (TGfx.Backend = TBackend.MetalMacOS) then
  begin
    GProgShaderDesc.vertex_func.source := @MVS_SOURCE_METAL_MACOS;
    GProgShaderDesc.vertex_func.entry := 'main0';
    GProgShaderDesc.fragment_func.source := @MFS_SOURCE_METAL_MACOS;
    GProgShaderDesc.fragment_func.entry := 'main0';
    GProgShaderDesc.attrs[0].base_type := _SG_SHADERATTRBASETYPE_FLOAT;
    GProgShaderDesc.attrs[1].base_type := _SG_SHADERATTRBASETYPE_FLOAT;
    GProgShaderDesc.uniform_blocks[0].stage := _SG_SHADERSTAGE_VERTEX;
    GProgShaderDesc.uniform_blocks[0].layout := _SG_UNIFORMLAYOUT_STD140;
    GProgShaderDesc.uniform_blocks[0].size := 128;
    GProgShaderDesc.uniform_blocks[0].msl_buffer_n := 0;
    GProgShaderDesc.uniform_blocks[1].stage := _SG_SHADERSTAGE_FRAGMENT;
    GProgShaderDesc.uniform_blocks[1].layout := _SG_UNIFORMLAYOUT_STD140;
    GProgShaderDesc.uniform_blocks[1].size := 32;
    GProgShaderDesc.uniform_blocks[1].msl_buffer_n := 1;
    GProgShaderDesc.&label := 'Mprog_shader';
  end;
  {$ENDIF !SOKOL_METAL}
  
  {$IFDEF SOKOL_METAL}
  if (TGfx.Backend = TBackend.MetalIOS) then
  begin
    GProgShaderDesc.vertex_func.source := @MVS_SOURCE_METAL_IOS;
    GProgShaderDesc.vertex_func.entry := 'main0';
    GProgShaderDesc.fragment_func.source := @MFS_SOURCE_METAL_IOS;
    GProgShaderDesc.fragment_func.entry := 'main0';
    GProgShaderDesc.attrs[0].base_type := _SG_SHADERATTRBASETYPE_FLOAT;
    GProgShaderDesc.attrs[1].base_type := _SG_SHADERATTRBASETYPE_FLOAT;
    GProgShaderDesc.uniform_blocks[0].stage := _SG_SHADERSTAGE_VERTEX;
    GProgShaderDesc.uniform_blocks[0].layout := _SG_UNIFORMLAYOUT_STD140;
    GProgShaderDesc.uniform_blocks[0].size := 128;
    GProgShaderDesc.uniform_blocks[0].msl_buffer_n := 0;
    GProgShaderDesc.uniform_blocks[1].stage := _SG_SHADERSTAGE_FRAGMENT;
    GProgShaderDesc.uniform_blocks[1].layout := _SG_UNIFORMLAYOUT_STD140;
    GProgShaderDesc.uniform_blocks[1].size := 32;
    GProgShaderDesc.uniform_blocks[1].msl_buffer_n := 1;
    GProgShaderDesc.&label := 'Mprog_shader';
  end;
  {$ENDIF !SOKOL_METAL}
  
  {$IFDEF SOKOL_VULKAN}
  if (TGfx.Backend = TBackend.Vulkan) then
  begin
    GProgShaderDesc.vertex_func.bytecode.ptr := @MVS_BYTECODE_SPIRV_VK;
    GProgShaderDesc.vertex_func.bytecode.size := 1156;
    GProgShaderDesc.vertex_func.entry := 'main';
    GProgShaderDesc.fragment_func.bytecode.ptr := @MFS_BYTECODE_SPIRV_VK;
    GProgShaderDesc.fragment_func.bytecode.size := 772;
    GProgShaderDesc.fragment_func.entry := 'main';
    GProgShaderDesc.attrs[0].base_type := _SG_SHADERATTRBASETYPE_FLOAT;
    GProgShaderDesc.attrs[1].base_type := _SG_SHADERATTRBASETYPE_FLOAT;
    GProgShaderDesc.uniform_blocks[0].stage := _SG_SHADERSTAGE_VERTEX;
    GProgShaderDesc.uniform_blocks[0].layout := _SG_UNIFORMLAYOUT_STD140;
    GProgShaderDesc.uniform_blocks[0].size := 128;
    GProgShaderDesc.uniform_blocks[0].spirv_set0_binding_n := 0;
    GProgShaderDesc.uniform_blocks[1].stage := _SG_SHADERSTAGE_FRAGMENT;
    GProgShaderDesc.uniform_blocks[1].layout := _SG_UNIFORMLAYOUT_STD140;
    GProgShaderDesc.uniform_blocks[1].size := 32;
    GProgShaderDesc.uniform_blocks[1].spirv_set0_binding_n := 1;
    GProgShaderDesc.&label := 'Mprog_shader';
  end;
  {$ENDIF !SOKOL_VULKAN}
end;

function MProgShaderDesc: PNativeShaderDesc;
begin
  if (GProgShaderDesc.&label = nil) then
    InitProgShaderDesc;

  Result := @GProgShaderDesc;
end;

function MProgAttrSlot(const AAttrName: String): Integer; inline;
begin
  if (AAttrName = 'position') then
    Exit(0);
  if (AAttrName = 'normal') then
    Exit(1);
  Result := -1;
end;

function MProgTextureSlot(const ATexName: String): Integer; inline;
begin
  Result := -1;
end;

function MProgSamplerSlot(const ASmpName: String): Integer; inline;
begin
  Result := -1;
end;

function MProgUniformBlockSlot(const AUBName: String): Integer; inline;
begin
  if (AUBName = 'vs_params') then
    Exit(0);
  if (AUBName = 'phong_params') then
    Exit(1);
  Result := -1;
end;

function MProgUniformBlockSize(const AUBName: String): NativeInt; inline;
begin
  if (AUBName = 'vs_params') then
    Exit(SizeOf(TMVSParams));
  if (AUBName = 'phong_params') then
    Exit(SizeOf(TMPhongParams));
  Result := 0;
end;

function MProgUniformOffset(const AUBName, AUName: String): Integer; inline;
begin
  if (AUBName = 'vs_params') then
  begin
    if (AUName = 'mvp') then
      Exit(0);
    if (AUName = 'model') then
      Exit(64);
  end;
  if (AUBName = 'phong_params') then
  begin
    if (AUName = 'mat_diffuse') then
      Exit(0);
    if (AUName = 'mat_specular') then
      Exit(16);
    if (AUName = 'mat_spec_power') then
      Exit(28);
  end;
  Result := -1;
end;

function MProgUniformDesc(const AUBName, AUName: String): TGlslShaderUniform; inline;
begin
  Result := Default(TGlslShaderUniform);
  if (AUBName = 'vs_params') then
  begin
    if (AUName = 'mvp') then
    begin
      Result.UniformType := TUniformType.Mat4;
      Result.ArrayCount := 0;
      Result.GlslName := 'mvp';
      Exit;
    end;
    if (AUName = 'model') then
    begin
      Result.UniformType := TUniformType.Mat4;
      Result.ArrayCount := 0;
      Result.GlslName := 'model';
      Exit;
    end;
  end;
  if (AUBName = 'phong_params') then
  begin
    if (AUName = 'mat_diffuse') then
    begin
      Result.UniformType := TUniformType.Float3;
      Result.ArrayCount := 0;
      Result.GlslName := 'mat_diffuse';
      Exit;
    end;
    if (AUName = 'mat_specular') then
    begin
      Result.UniformType := TUniformType.Float3;
      Result.ArrayCount := 0;
      Result.GlslName := 'mat_specular';
      Exit;
    end;
    if (AUName = 'mat_spec_power') then
    begin
      Result.UniformType := TUniformType.Float;
      Result.ArrayCount := 0;
      Result.GlslName := 'mat_spec_power';
      Exit;
    end;
  end;
end;

function MProgStorageBufferSlot(const ASBufName: String): Integer; inline;
begin
  Result := -1;
end;

function MProgStorageImageSlot(const ASImgName: String): Integer; inline;
begin
  Result := -1;
end;

end.
