unit BufferOffsetsShader;
(*
  #version:1# (machine generated, don't edit!)

  Generated by sokol-shdc (https://github.com/floooh/sokol-tools)

  Cmdline:
    sokol-shdc --input BufferOffsetsShader.glsl --output BufferOffsetsShader.pas

  Overview:
  =========
  Shader program: 'bufferoffsets':
    Get shader desc: bufferoffsets_shader_desc(sg_query_backend());
    Vertex Shader: vs
    Fragment Shader: fs
    Attributes:
      ATTR_BUFFEROFFSETS_POSITION => 0
      ATTR_BUFFEROFFSETS_COLOR0 => 1
  Bindings:
*)

{$INCLUDE 'Neslib.Sokol.inc'}

interface

uses
  Neslib.FastMath,
  Neslib.Sokol.Gfx;

const
  ATTR_BUFFEROFFSETS_POSITION = 0;
  ATTR_BUFFEROFFSETS_COLOR0 = 1;

function BufferoffsetsShaderDesc: PNativeShaderDesc;

implementation

uses
  Neslib.Sokol.Api;

(*
  #version 410

  layout(location = 0) in vec4 position;
  layout(location = 0) out vec4 color;
  layout(location = 1) in vec4 color0;

  void main()
  {
      gl_Position = position;
      color = color0;
  }

*)
{$IFDEF SOKOL_GLCORE}
const
  VS_SOURCE_GLSL410: array [0..193] of Byte = (
    $23,$76,$65,$72,$73,$69,$6f,$6e,$20,$34,$31,$30,$0a,$0a,$6c,$61,
    $79,$6f,$75,$74,$28,$6c,$6f,$63,$61,$74,$69,$6f,$6e,$20,$3d,$20,
    $30,$29,$20,$69,$6e,$20,$76,$65,$63,$34,$20,$70,$6f,$73,$69,$74,
    $69,$6f,$6e,$3b,$0a,$6c,$61,$79,$6f,$75,$74,$28,$6c,$6f,$63,$61,
    $74,$69,$6f,$6e,$20,$3d,$20,$30,$29,$20,$6f,$75,$74,$20,$76,$65,
    $63,$34,$20,$63,$6f,$6c,$6f,$72,$3b,$0a,$6c,$61,$79,$6f,$75,$74,
    $28,$6c,$6f,$63,$61,$74,$69,$6f,$6e,$20,$3d,$20,$31,$29,$20,$69,
    $6e,$20,$76,$65,$63,$34,$20,$63,$6f,$6c,$6f,$72,$30,$3b,$0a,$0a,
    $76,$6f,$69,$64,$20,$6d,$61,$69,$6e,$28,$29,$0a,$7b,$0a,$20,$20,
    $20,$20,$67,$6c,$5f,$50,$6f,$73,$69,$74,$69,$6f,$6e,$20,$3d,$20,
    $70,$6f,$73,$69,$74,$69,$6f,$6e,$3b,$0a,$20,$20,$20,$20,$63,$6f,
    $6c,$6f,$72,$20,$3d,$20,$63,$6f,$6c,$6f,$72,$30,$3b,$0a,$7d,$0a,
    $0a,$00);
{$ENDIF}

(*
  #version 410

  layout(location = 0) out vec4 frag_color;
  layout(location = 0) in vec4 color;

  void main()
  {
      frag_color = color;
  }

*)
{$IFDEF SOKOL_GLCORE}
const
  FS_SOURCE_GLSL410: array [0..134] of Byte = (
    $23,$76,$65,$72,$73,$69,$6f,$6e,$20,$34,$31,$30,$0a,$0a,$6c,$61,
    $79,$6f,$75,$74,$28,$6c,$6f,$63,$61,$74,$69,$6f,$6e,$20,$3d,$20,
    $30,$29,$20,$6f,$75,$74,$20,$76,$65,$63,$34,$20,$66,$72,$61,$67,
    $5f,$63,$6f,$6c,$6f,$72,$3b,$0a,$6c,$61,$79,$6f,$75,$74,$28,$6c,
    $6f,$63,$61,$74,$69,$6f,$6e,$20,$3d,$20,$30,$29,$20,$69,$6e,$20,
    $76,$65,$63,$34,$20,$63,$6f,$6c,$6f,$72,$3b,$0a,$0a,$76,$6f,$69,
    $64,$20,$6d,$61,$69,$6e,$28,$29,$0a,$7b,$0a,$20,$20,$20,$20,$66,
    $72,$61,$67,$5f,$63,$6f,$6c,$6f,$72,$20,$3d,$20,$63,$6f,$6c,$6f,
    $72,$3b,$0a,$7d,$0a,$0a,$00);
{$ENDIF}

(*
  #version 300 es

  layout(location = 0) in vec4 position;
  out vec4 color;
  layout(location = 1) in vec4 color0;

  void main()
  {
      gl_Position = position;
      color = color0;
  }

*)
{$IFDEF SOKOL_GLES3}
const
  VS_SOURCE_GLSL300ES: array [0..175] of Byte = (
    $23,$76,$65,$72,$73,$69,$6f,$6e,$20,$33,$30,$30,$20,$65,$73,$0a,
    $0a,$6c,$61,$79,$6f,$75,$74,$28,$6c,$6f,$63,$61,$74,$69,$6f,$6e,
    $20,$3d,$20,$30,$29,$20,$69,$6e,$20,$76,$65,$63,$34,$20,$70,$6f,
    $73,$69,$74,$69,$6f,$6e,$3b,$0a,$6f,$75,$74,$20,$76,$65,$63,$34,
    $20,$63,$6f,$6c,$6f,$72,$3b,$0a,$6c,$61,$79,$6f,$75,$74,$28,$6c,
    $6f,$63,$61,$74,$69,$6f,$6e,$20,$3d,$20,$31,$29,$20,$69,$6e,$20,
    $76,$65,$63,$34,$20,$63,$6f,$6c,$6f,$72,$30,$3b,$0a,$0a,$76,$6f,
    $69,$64,$20,$6d,$61,$69,$6e,$28,$29,$0a,$7b,$0a,$20,$20,$20,$20,
    $67,$6c,$5f,$50,$6f,$73,$69,$74,$69,$6f,$6e,$20,$3d,$20,$70,$6f,
    $73,$69,$74,$69,$6f,$6e,$3b,$0a,$20,$20,$20,$20,$63,$6f,$6c,$6f,
    $72,$20,$3d,$20,$63,$6f,$6c,$6f,$72,$30,$3b,$0a,$7d,$0a,$0a,$00);
{$ENDIF}

(*
  #version 300 es
  precision mediump float;
  precision highp int;

  layout(location = 0) out highp vec4 frag_color;
  in highp vec4 color;

  void main()
  {
      frag_color = color;
  }

*)
{$IFDEF SOKOL_GLES3}
const
  FS_SOURCE_GLSL300ES: array [0..174] of Byte = (
    $23,$76,$65,$72,$73,$69,$6f,$6e,$20,$33,$30,$30,$20,$65,$73,$0a,
    $70,$72,$65,$63,$69,$73,$69,$6f,$6e,$20,$6d,$65,$64,$69,$75,$6d,
    $70,$20,$66,$6c,$6f,$61,$74,$3b,$0a,$70,$72,$65,$63,$69,$73,$69,
    $6f,$6e,$20,$68,$69,$67,$68,$70,$20,$69,$6e,$74,$3b,$0a,$0a,$6c,
    $61,$79,$6f,$75,$74,$28,$6c,$6f,$63,$61,$74,$69,$6f,$6e,$20,$3d,
    $20,$30,$29,$20,$6f,$75,$74,$20,$68,$69,$67,$68,$70,$20,$76,$65,
    $63,$34,$20,$66,$72,$61,$67,$5f,$63,$6f,$6c,$6f,$72,$3b,$0a,$69,
    $6e,$20,$68,$69,$67,$68,$70,$20,$76,$65,$63,$34,$20,$63,$6f,$6c,
    $6f,$72,$3b,$0a,$0a,$76,$6f,$69,$64,$20,$6d,$61,$69,$6e,$28,$29,
    $0a,$7b,$0a,$20,$20,$20,$20,$66,$72,$61,$67,$5f,$63,$6f,$6c,$6f,
    $72,$20,$3d,$20,$63,$6f,$6c,$6f,$72,$3b,$0a,$7d,$0a,$0a,$00);
{$ENDIF}

(*
  static float4 gl_Position;
  static float4 position;
  static float4 color;
  static float4 color0;

  struct SPIRV_Cross_Input
  {
      float4 position : TEXCOORD0;
      float4 color0 : TEXCOORD1;
  };

  struct SPIRV_Cross_Output
  {
      float4 color : TEXCOORD0;
      float4 gl_Position : SV_Position;
  };

  void vert_main()
  {
      gl_Position = position;
      color = color0;
  }

  SPIRV_Cross_Output main(SPIRV_Cross_Input stage_input)
  {
      position = stage_input.position;
      color0 = stage_input.color0;
      vert_main();
      SPIRV_Cross_Output stage_output;
      stage_output.gl_Position = gl_Position;
      stage_output.color = color;
      return stage_output;
  }
*)
{$IFDEF SOKOL_D3D11}
const
  VS_SOURCE_HLSL5: array [0..644] of Byte = (
    $73,$74,$61,$74,$69,$63,$20,$66,$6c,$6f,$61,$74,$34,$20,$67,$6c,
    $5f,$50,$6f,$73,$69,$74,$69,$6f,$6e,$3b,$0a,$73,$74,$61,$74,$69,
    $63,$20,$66,$6c,$6f,$61,$74,$34,$20,$70,$6f,$73,$69,$74,$69,$6f,
    $6e,$3b,$0a,$73,$74,$61,$74,$69,$63,$20,$66,$6c,$6f,$61,$74,$34,
    $20,$63,$6f,$6c,$6f,$72,$3b,$0a,$73,$74,$61,$74,$69,$63,$20,$66,
    $6c,$6f,$61,$74,$34,$20,$63,$6f,$6c,$6f,$72,$30,$3b,$0a,$0a,$73,
    $74,$72,$75,$63,$74,$20,$53,$50,$49,$52,$56,$5f,$43,$72,$6f,$73,
    $73,$5f,$49,$6e,$70,$75,$74,$0a,$7b,$0a,$20,$20,$20,$20,$66,$6c,
    $6f,$61,$74,$34,$20,$70,$6f,$73,$69,$74,$69,$6f,$6e,$20,$3a,$20,
    $54,$45,$58,$43,$4f,$4f,$52,$44,$30,$3b,$0a,$20,$20,$20,$20,$66,
    $6c,$6f,$61,$74,$34,$20,$63,$6f,$6c,$6f,$72,$30,$20,$3a,$20,$54,
    $45,$58,$43,$4f,$4f,$52,$44,$31,$3b,$0a,$7d,$3b,$0a,$0a,$73,$74,
    $72,$75,$63,$74,$20,$53,$50,$49,$52,$56,$5f,$43,$72,$6f,$73,$73,
    $5f,$4f,$75,$74,$70,$75,$74,$0a,$7b,$0a,$20,$20,$20,$20,$66,$6c,
    $6f,$61,$74,$34,$20,$63,$6f,$6c,$6f,$72,$20,$3a,$20,$54,$45,$58,
    $43,$4f,$4f,$52,$44,$30,$3b,$0a,$20,$20,$20,$20,$66,$6c,$6f,$61,
    $74,$34,$20,$67,$6c,$5f,$50,$6f,$73,$69,$74,$69,$6f,$6e,$20,$3a,
    $20,$53,$56,$5f,$50,$6f,$73,$69,$74,$69,$6f,$6e,$3b,$0a,$7d,$3b,
    $0a,$0a,$76,$6f,$69,$64,$20,$76,$65,$72,$74,$5f,$6d,$61,$69,$6e,
    $28,$29,$0a,$7b,$0a,$20,$20,$20,$20,$67,$6c,$5f,$50,$6f,$73,$69,
    $74,$69,$6f,$6e,$20,$3d,$20,$70,$6f,$73,$69,$74,$69,$6f,$6e,$3b,
    $0a,$20,$20,$20,$20,$63,$6f,$6c,$6f,$72,$20,$3d,$20,$63,$6f,$6c,
    $6f,$72,$30,$3b,$0a,$7d,$0a,$0a,$53,$50,$49,$52,$56,$5f,$43,$72,
    $6f,$73,$73,$5f,$4f,$75,$74,$70,$75,$74,$20,$6d,$61,$69,$6e,$28,
    $53,$50,$49,$52,$56,$5f,$43,$72,$6f,$73,$73,$5f,$49,$6e,$70,$75,
    $74,$20,$73,$74,$61,$67,$65,$5f,$69,$6e,$70,$75,$74,$29,$0a,$7b,
    $0a,$20,$20,$20,$20,$70,$6f,$73,$69,$74,$69,$6f,$6e,$20,$3d,$20,
    $73,$74,$61,$67,$65,$5f,$69,$6e,$70,$75,$74,$2e,$70,$6f,$73,$69,
    $74,$69,$6f,$6e,$3b,$0a,$20,$20,$20,$20,$63,$6f,$6c,$6f,$72,$30,
    $20,$3d,$20,$73,$74,$61,$67,$65,$5f,$69,$6e,$70,$75,$74,$2e,$63,
    $6f,$6c,$6f,$72,$30,$3b,$0a,$20,$20,$20,$20,$76,$65,$72,$74,$5f,
    $6d,$61,$69,$6e,$28,$29,$3b,$0a,$20,$20,$20,$20,$53,$50,$49,$52,
    $56,$5f,$43,$72,$6f,$73,$73,$5f,$4f,$75,$74,$70,$75,$74,$20,$73,
    $74,$61,$67,$65,$5f,$6f,$75,$74,$70,$75,$74,$3b,$0a,$20,$20,$20,
    $20,$73,$74,$61,$67,$65,$5f,$6f,$75,$74,$70,$75,$74,$2e,$67,$6c,
    $5f,$50,$6f,$73,$69,$74,$69,$6f,$6e,$20,$3d,$20,$67,$6c,$5f,$50,
    $6f,$73,$69,$74,$69,$6f,$6e,$3b,$0a,$20,$20,$20,$20,$73,$74,$61,
    $67,$65,$5f,$6f,$75,$74,$70,$75,$74,$2e,$63,$6f,$6c,$6f,$72,$20,
    $3d,$20,$63,$6f,$6c,$6f,$72,$3b,$0a,$20,$20,$20,$20,$72,$65,$74,
    $75,$72,$6e,$20,$73,$74,$61,$67,$65,$5f,$6f,$75,$74,$70,$75,$74,
    $3b,$0a,$7d,$0a,$00);
{$ENDIF}

(*
  static float4 frag_color;
  static float4 color;

  struct SPIRV_Cross_Input
  {
      float4 color : TEXCOORD0;
  };

  struct SPIRV_Cross_Output
  {
      float4 frag_color : SV_Target0;
  };

  void frag_main()
  {
      frag_color = color;
  }

  SPIRV_Cross_Output main(SPIRV_Cross_Input stage_input)
  {
      color = stage_input.color;
      frag_main();
      SPIRV_Cross_Output stage_output;
      stage_output.frag_color = frag_color;
      return stage_output;
  }
*)
{$IFDEF SOKOL_D3D11}
const
  FS_SOURCE_HLSL5: array [0..434] of Byte = (
    $73,$74,$61,$74,$69,$63,$20,$66,$6c,$6f,$61,$74,$34,$20,$66,$72,
    $61,$67,$5f,$63,$6f,$6c,$6f,$72,$3b,$0a,$73,$74,$61,$74,$69,$63,
    $20,$66,$6c,$6f,$61,$74,$34,$20,$63,$6f,$6c,$6f,$72,$3b,$0a,$0a,
    $73,$74,$72,$75,$63,$74,$20,$53,$50,$49,$52,$56,$5f,$43,$72,$6f,
    $73,$73,$5f,$49,$6e,$70,$75,$74,$0a,$7b,$0a,$20,$20,$20,$20,$66,
    $6c,$6f,$61,$74,$34,$20,$63,$6f,$6c,$6f,$72,$20,$3a,$20,$54,$45,
    $58,$43,$4f,$4f,$52,$44,$30,$3b,$0a,$7d,$3b,$0a,$0a,$73,$74,$72,
    $75,$63,$74,$20,$53,$50,$49,$52,$56,$5f,$43,$72,$6f,$73,$73,$5f,
    $4f,$75,$74,$70,$75,$74,$0a,$7b,$0a,$20,$20,$20,$20,$66,$6c,$6f,
    $61,$74,$34,$20,$66,$72,$61,$67,$5f,$63,$6f,$6c,$6f,$72,$20,$3a,
    $20,$53,$56,$5f,$54,$61,$72,$67,$65,$74,$30,$3b,$0a,$7d,$3b,$0a,
    $0a,$76,$6f,$69,$64,$20,$66,$72,$61,$67,$5f,$6d,$61,$69,$6e,$28,
    $29,$0a,$7b,$0a,$20,$20,$20,$20,$66,$72,$61,$67,$5f,$63,$6f,$6c,
    $6f,$72,$20,$3d,$20,$63,$6f,$6c,$6f,$72,$3b,$0a,$7d,$0a,$0a,$53,
    $50,$49,$52,$56,$5f,$43,$72,$6f,$73,$73,$5f,$4f,$75,$74,$70,$75,
    $74,$20,$6d,$61,$69,$6e,$28,$53,$50,$49,$52,$56,$5f,$43,$72,$6f,
    $73,$73,$5f,$49,$6e,$70,$75,$74,$20,$73,$74,$61,$67,$65,$5f,$69,
    $6e,$70,$75,$74,$29,$0a,$7b,$0a,$20,$20,$20,$20,$63,$6f,$6c,$6f,
    $72,$20,$3d,$20,$73,$74,$61,$67,$65,$5f,$69,$6e,$70,$75,$74,$2e,
    $63,$6f,$6c,$6f,$72,$3b,$0a,$20,$20,$20,$20,$66,$72,$61,$67,$5f,
    $6d,$61,$69,$6e,$28,$29,$3b,$0a,$20,$20,$20,$20,$53,$50,$49,$52,
    $56,$5f,$43,$72,$6f,$73,$73,$5f,$4f,$75,$74,$70,$75,$74,$20,$73,
    $74,$61,$67,$65,$5f,$6f,$75,$74,$70,$75,$74,$3b,$0a,$20,$20,$20,
    $20,$73,$74,$61,$67,$65,$5f,$6f,$75,$74,$70,$75,$74,$2e,$66,$72,
    $61,$67,$5f,$63,$6f,$6c,$6f,$72,$20,$3d,$20,$66,$72,$61,$67,$5f,
    $63,$6f,$6c,$6f,$72,$3b,$0a,$20,$20,$20,$20,$72,$65,$74,$75,$72,
    $6e,$20,$73,$74,$61,$67,$65,$5f,$6f,$75,$74,$70,$75,$74,$3b,$0a,
    $7d,$0a,$00);
{$ENDIF}

(*
  #include <metal_stdlib>
  #include <simd/simd.h>

  using namespace metal;

  struct main0_out
  {
      float4 color [[user(locn0)]];
      float4 gl_Position [[position]];
  };

  struct main0_in
  {
      float4 position [[attribute(0)]];
      float4 color0 [[attribute(1)]];
  };

  vertex main0_out main0(main0_in in [[stage_in]])
  {
      main0_out out = {};
      out.gl_Position = in.position;
      out.color = in.color0;
      return out;
  }

*)
{$IFDEF SOKOL_METAL}
const
  VS_SOURCE_METAL_MACOS: array [0..418] of Byte = (
    $23,$69,$6e,$63,$6c,$75,$64,$65,$20,$3c,$6d,$65,$74,$61,$6c,$5f,
    $73,$74,$64,$6c,$69,$62,$3e,$0a,$23,$69,$6e,$63,$6c,$75,$64,$65,
    $20,$3c,$73,$69,$6d,$64,$2f,$73,$69,$6d,$64,$2e,$68,$3e,$0a,$0a,
    $75,$73,$69,$6e,$67,$20,$6e,$61,$6d,$65,$73,$70,$61,$63,$65,$20,
    $6d,$65,$74,$61,$6c,$3b,$0a,$0a,$73,$74,$72,$75,$63,$74,$20,$6d,
    $61,$69,$6e,$30,$5f,$6f,$75,$74,$0a,$7b,$0a,$20,$20,$20,$20,$66,
    $6c,$6f,$61,$74,$34,$20,$63,$6f,$6c,$6f,$72,$20,$5b,$5b,$75,$73,
    $65,$72,$28,$6c,$6f,$63,$6e,$30,$29,$5d,$5d,$3b,$0a,$20,$20,$20,
    $20,$66,$6c,$6f,$61,$74,$34,$20,$67,$6c,$5f,$50,$6f,$73,$69,$74,
    $69,$6f,$6e,$20,$5b,$5b,$70,$6f,$73,$69,$74,$69,$6f,$6e,$5d,$5d,
    $3b,$0a,$7d,$3b,$0a,$0a,$73,$74,$72,$75,$63,$74,$20,$6d,$61,$69,
    $6e,$30,$5f,$69,$6e,$0a,$7b,$0a,$20,$20,$20,$20,$66,$6c,$6f,$61,
    $74,$34,$20,$70,$6f,$73,$69,$74,$69,$6f,$6e,$20,$5b,$5b,$61,$74,
    $74,$72,$69,$62,$75,$74,$65,$28,$30,$29,$5d,$5d,$3b,$0a,$20,$20,
    $20,$20,$66,$6c,$6f,$61,$74,$34,$20,$63,$6f,$6c,$6f,$72,$30,$20,
    $5b,$5b,$61,$74,$74,$72,$69,$62,$75,$74,$65,$28,$31,$29,$5d,$5d,
    $3b,$0a,$7d,$3b,$0a,$0a,$76,$65,$72,$74,$65,$78,$20,$6d,$61,$69,
    $6e,$30,$5f,$6f,$75,$74,$20,$6d,$61,$69,$6e,$30,$28,$6d,$61,$69,
    $6e,$30,$5f,$69,$6e,$20,$69,$6e,$20,$5b,$5b,$73,$74,$61,$67,$65,
    $5f,$69,$6e,$5d,$5d,$29,$0a,$7b,$0a,$20,$20,$20,$20,$6d,$61,$69,
    $6e,$30,$5f,$6f,$75,$74,$20,$6f,$75,$74,$20,$3d,$20,$7b,$7d,$3b,
    $0a,$20,$20,$20,$20,$6f,$75,$74,$2e,$67,$6c,$5f,$50,$6f,$73,$69,
    $74,$69,$6f,$6e,$20,$3d,$20,$69,$6e,$2e,$70,$6f,$73,$69,$74,$69,
    $6f,$6e,$3b,$0a,$20,$20,$20,$20,$6f,$75,$74,$2e,$63,$6f,$6c,$6f,
    $72,$20,$3d,$20,$69,$6e,$2e,$63,$6f,$6c,$6f,$72,$30,$3b,$0a,$20,
    $20,$20,$20,$72,$65,$74,$75,$72,$6e,$20,$6f,$75,$74,$3b,$0a,$7d,
    $0a,$0a,$00);
{$ENDIF}

(*
  #include <metal_stdlib>
  #include <simd/simd.h>

  using namespace metal;

  struct main0_out
  {
      float4 frag_color [[color(0)]];
  };

  struct main0_in
  {
      float4 color [[user(locn0)]];
  };

  fragment main0_out main0(main0_in in [[stage_in]])
  {
      main0_out out = {};
      out.frag_color = in.color;
      return out;
  }

*)
{$IFDEF SOKOL_METAL}
const
  FS_SOURCE_METAL_MACOS: array [0..314] of Byte = (
    $23,$69,$6e,$63,$6c,$75,$64,$65,$20,$3c,$6d,$65,$74,$61,$6c,$5f,
    $73,$74,$64,$6c,$69,$62,$3e,$0a,$23,$69,$6e,$63,$6c,$75,$64,$65,
    $20,$3c,$73,$69,$6d,$64,$2f,$73,$69,$6d,$64,$2e,$68,$3e,$0a,$0a,
    $75,$73,$69,$6e,$67,$20,$6e,$61,$6d,$65,$73,$70,$61,$63,$65,$20,
    $6d,$65,$74,$61,$6c,$3b,$0a,$0a,$73,$74,$72,$75,$63,$74,$20,$6d,
    $61,$69,$6e,$30,$5f,$6f,$75,$74,$0a,$7b,$0a,$20,$20,$20,$20,$66,
    $6c,$6f,$61,$74,$34,$20,$66,$72,$61,$67,$5f,$63,$6f,$6c,$6f,$72,
    $20,$5b,$5b,$63,$6f,$6c,$6f,$72,$28,$30,$29,$5d,$5d,$3b,$0a,$7d,
    $3b,$0a,$0a,$73,$74,$72,$75,$63,$74,$20,$6d,$61,$69,$6e,$30,$5f,
    $69,$6e,$0a,$7b,$0a,$20,$20,$20,$20,$66,$6c,$6f,$61,$74,$34,$20,
    $63,$6f,$6c,$6f,$72,$20,$5b,$5b,$75,$73,$65,$72,$28,$6c,$6f,$63,
    $6e,$30,$29,$5d,$5d,$3b,$0a,$7d,$3b,$0a,$0a,$66,$72,$61,$67,$6d,
    $65,$6e,$74,$20,$6d,$61,$69,$6e,$30,$5f,$6f,$75,$74,$20,$6d,$61,
    $69,$6e,$30,$28,$6d,$61,$69,$6e,$30,$5f,$69,$6e,$20,$69,$6e,$20,
    $5b,$5b,$73,$74,$61,$67,$65,$5f,$69,$6e,$5d,$5d,$29,$0a,$7b,$0a,
    $20,$20,$20,$20,$6d,$61,$69,$6e,$30,$5f,$6f,$75,$74,$20,$6f,$75,
    $74,$20,$3d,$20,$7b,$7d,$3b,$0a,$20,$20,$20,$20,$6f,$75,$74,$2e,
    $66,$72,$61,$67,$5f,$63,$6f,$6c,$6f,$72,$20,$3d,$20,$69,$6e,$2e,
    $63,$6f,$6c,$6f,$72,$3b,$0a,$20,$20,$20,$20,$72,$65,$74,$75,$72,
    $6e,$20,$6f,$75,$74,$3b,$0a,$7d,$0a,$0a,$00);
{$ENDIF}

(*
  #include <metal_stdlib>
  #include <simd/simd.h>

  using namespace metal;

  struct main0_out
  {
      float4 color [[user(locn0)]];
      float4 gl_Position [[position]];
  };

  struct main0_in
  {
      float4 position [[attribute(0)]];
      float4 color0 [[attribute(1)]];
  };

  vertex main0_out main0(main0_in in [[stage_in]])
  {
      main0_out out = {};
      out.gl_Position = in.position;
      out.color = in.color0;
      return out;
  }

*)
{$IFDEF SOKOL_METAL}
const
  VS_SOURCE_METAL_IOS: array [0..418] of Byte = (
    $23,$69,$6e,$63,$6c,$75,$64,$65,$20,$3c,$6d,$65,$74,$61,$6c,$5f,
    $73,$74,$64,$6c,$69,$62,$3e,$0a,$23,$69,$6e,$63,$6c,$75,$64,$65,
    $20,$3c,$73,$69,$6d,$64,$2f,$73,$69,$6d,$64,$2e,$68,$3e,$0a,$0a,
    $75,$73,$69,$6e,$67,$20,$6e,$61,$6d,$65,$73,$70,$61,$63,$65,$20,
    $6d,$65,$74,$61,$6c,$3b,$0a,$0a,$73,$74,$72,$75,$63,$74,$20,$6d,
    $61,$69,$6e,$30,$5f,$6f,$75,$74,$0a,$7b,$0a,$20,$20,$20,$20,$66,
    $6c,$6f,$61,$74,$34,$20,$63,$6f,$6c,$6f,$72,$20,$5b,$5b,$75,$73,
    $65,$72,$28,$6c,$6f,$63,$6e,$30,$29,$5d,$5d,$3b,$0a,$20,$20,$20,
    $20,$66,$6c,$6f,$61,$74,$34,$20,$67,$6c,$5f,$50,$6f,$73,$69,$74,
    $69,$6f,$6e,$20,$5b,$5b,$70,$6f,$73,$69,$74,$69,$6f,$6e,$5d,$5d,
    $3b,$0a,$7d,$3b,$0a,$0a,$73,$74,$72,$75,$63,$74,$20,$6d,$61,$69,
    $6e,$30,$5f,$69,$6e,$0a,$7b,$0a,$20,$20,$20,$20,$66,$6c,$6f,$61,
    $74,$34,$20,$70,$6f,$73,$69,$74,$69,$6f,$6e,$20,$5b,$5b,$61,$74,
    $74,$72,$69,$62,$75,$74,$65,$28,$30,$29,$5d,$5d,$3b,$0a,$20,$20,
    $20,$20,$66,$6c,$6f,$61,$74,$34,$20,$63,$6f,$6c,$6f,$72,$30,$20,
    $5b,$5b,$61,$74,$74,$72,$69,$62,$75,$74,$65,$28,$31,$29,$5d,$5d,
    $3b,$0a,$7d,$3b,$0a,$0a,$76,$65,$72,$74,$65,$78,$20,$6d,$61,$69,
    $6e,$30,$5f,$6f,$75,$74,$20,$6d,$61,$69,$6e,$30,$28,$6d,$61,$69,
    $6e,$30,$5f,$69,$6e,$20,$69,$6e,$20,$5b,$5b,$73,$74,$61,$67,$65,
    $5f,$69,$6e,$5d,$5d,$29,$0a,$7b,$0a,$20,$20,$20,$20,$6d,$61,$69,
    $6e,$30,$5f,$6f,$75,$74,$20,$6f,$75,$74,$20,$3d,$20,$7b,$7d,$3b,
    $0a,$20,$20,$20,$20,$6f,$75,$74,$2e,$67,$6c,$5f,$50,$6f,$73,$69,
    $74,$69,$6f,$6e,$20,$3d,$20,$69,$6e,$2e,$70,$6f,$73,$69,$74,$69,
    $6f,$6e,$3b,$0a,$20,$20,$20,$20,$6f,$75,$74,$2e,$63,$6f,$6c,$6f,
    $72,$20,$3d,$20,$69,$6e,$2e,$63,$6f,$6c,$6f,$72,$30,$3b,$0a,$20,
    $20,$20,$20,$72,$65,$74,$75,$72,$6e,$20,$6f,$75,$74,$3b,$0a,$7d,
    $0a,$0a,$00);
{$ENDIF}

(*
  #include <metal_stdlib>
  #include <simd/simd.h>

  using namespace metal;

  struct main0_out
  {
      float4 frag_color [[color(0)]];
  };

  struct main0_in
  {
      float4 color [[user(locn0)]];
  };

  fragment main0_out main0(main0_in in [[stage_in]])
  {
      main0_out out = {};
      out.frag_color = in.color;
      return out;
  }

*)
{$IFDEF SOKOL_METAL}
const
  FS_SOURCE_METAL_IOS: array [0..314] of Byte = (
    $23,$69,$6e,$63,$6c,$75,$64,$65,$20,$3c,$6d,$65,$74,$61,$6c,$5f,
    $73,$74,$64,$6c,$69,$62,$3e,$0a,$23,$69,$6e,$63,$6c,$75,$64,$65,
    $20,$3c,$73,$69,$6d,$64,$2f,$73,$69,$6d,$64,$2e,$68,$3e,$0a,$0a,
    $75,$73,$69,$6e,$67,$20,$6e,$61,$6d,$65,$73,$70,$61,$63,$65,$20,
    $6d,$65,$74,$61,$6c,$3b,$0a,$0a,$73,$74,$72,$75,$63,$74,$20,$6d,
    $61,$69,$6e,$30,$5f,$6f,$75,$74,$0a,$7b,$0a,$20,$20,$20,$20,$66,
    $6c,$6f,$61,$74,$34,$20,$66,$72,$61,$67,$5f,$63,$6f,$6c,$6f,$72,
    $20,$5b,$5b,$63,$6f,$6c,$6f,$72,$28,$30,$29,$5d,$5d,$3b,$0a,$7d,
    $3b,$0a,$0a,$73,$74,$72,$75,$63,$74,$20,$6d,$61,$69,$6e,$30,$5f,
    $69,$6e,$0a,$7b,$0a,$20,$20,$20,$20,$66,$6c,$6f,$61,$74,$34,$20,
    $63,$6f,$6c,$6f,$72,$20,$5b,$5b,$75,$73,$65,$72,$28,$6c,$6f,$63,
    $6e,$30,$29,$5d,$5d,$3b,$0a,$7d,$3b,$0a,$0a,$66,$72,$61,$67,$6d,
    $65,$6e,$74,$20,$6d,$61,$69,$6e,$30,$5f,$6f,$75,$74,$20,$6d,$61,
    $69,$6e,$30,$28,$6d,$61,$69,$6e,$30,$5f,$69,$6e,$20,$69,$6e,$20,
    $5b,$5b,$73,$74,$61,$67,$65,$5f,$69,$6e,$5d,$5d,$29,$0a,$7b,$0a,
    $20,$20,$20,$20,$6d,$61,$69,$6e,$30,$5f,$6f,$75,$74,$20,$6f,$75,
    $74,$20,$3d,$20,$7b,$7d,$3b,$0a,$20,$20,$20,$20,$6f,$75,$74,$2e,
    $66,$72,$61,$67,$5f,$63,$6f,$6c,$6f,$72,$20,$3d,$20,$69,$6e,$2e,
    $63,$6f,$6c,$6f,$72,$3b,$0a,$20,$20,$20,$20,$72,$65,$74,$75,$72,
    $6e,$20,$6f,$75,$74,$3b,$0a,$7d,$0a,$0a,$00);
{$ENDIF}

(*
  #version 460

  layout(location = 0) in vec4 position;
  layout(location = 0) out vec4 color;
  layout(location = 1) in vec4 color0;

  void main()
  {
      gl_Position = position;
      color = color0;
  }

*)
{$IFDEF SOKOL_VULKAN}
const
  VS_BYTECODE_SPIRV_VK: array [0..839] of Byte = (
    $03,$02,$23,$07,$00,$04,$01,$00,$0b,$00,$08,$00,$18,$00,$00,$00,
    $00,$00,$00,$00,$11,$00,$02,$00,$01,$00,$00,$00,$0b,$00,$06,$00,
    $01,$00,$00,$00,$47,$4c,$53,$4c,$2e,$73,$74,$64,$2e,$34,$35,$30,
    $00,$00,$00,$00,$0e,$00,$03,$00,$00,$00,$00,$00,$01,$00,$00,$00,
    $0f,$00,$09,$00,$00,$00,$00,$00,$04,$00,$00,$00,$6d,$61,$69,$6e,
    $00,$00,$00,$00,$0d,$00,$00,$00,$11,$00,$00,$00,$15,$00,$00,$00,
    $16,$00,$00,$00,$03,$00,$03,$00,$02,$00,$00,$00,$cc,$01,$00,$00,
    $05,$00,$04,$00,$04,$00,$00,$00,$6d,$61,$69,$6e,$00,$00,$00,$00,
    $05,$00,$06,$00,$0b,$00,$00,$00,$67,$6c,$5f,$50,$65,$72,$56,$65,
    $72,$74,$65,$78,$00,$00,$00,$00,$06,$00,$06,$00,$0b,$00,$00,$00,
    $00,$00,$00,$00,$67,$6c,$5f,$50,$6f,$73,$69,$74,$69,$6f,$6e,$00,
    $06,$00,$07,$00,$0b,$00,$00,$00,$01,$00,$00,$00,$67,$6c,$5f,$50,
    $6f,$69,$6e,$74,$53,$69,$7a,$65,$00,$00,$00,$00,$06,$00,$07,$00,
    $0b,$00,$00,$00,$02,$00,$00,$00,$67,$6c,$5f,$43,$6c,$69,$70,$44,
    $69,$73,$74,$61,$6e,$63,$65,$00,$06,$00,$07,$00,$0b,$00,$00,$00,
    $03,$00,$00,$00,$67,$6c,$5f,$43,$75,$6c,$6c,$44,$69,$73,$74,$61,
    $6e,$63,$65,$00,$05,$00,$03,$00,$0d,$00,$00,$00,$00,$00,$00,$00,
    $05,$00,$05,$00,$11,$00,$00,$00,$70,$6f,$73,$69,$74,$69,$6f,$6e,
    $00,$00,$00,$00,$05,$00,$04,$00,$15,$00,$00,$00,$63,$6f,$6c,$6f,
    $72,$00,$00,$00,$05,$00,$04,$00,$16,$00,$00,$00,$63,$6f,$6c,$6f,
    $72,$30,$00,$00,$47,$00,$03,$00,$0b,$00,$00,$00,$02,$00,$00,$00,
    $48,$00,$05,$00,$0b,$00,$00,$00,$00,$00,$00,$00,$0b,$00,$00,$00,
    $00,$00,$00,$00,$48,$00,$05,$00,$0b,$00,$00,$00,$01,$00,$00,$00,
    $0b,$00,$00,$00,$01,$00,$00,$00,$48,$00,$05,$00,$0b,$00,$00,$00,
    $02,$00,$00,$00,$0b,$00,$00,$00,$03,$00,$00,$00,$48,$00,$05,$00,
    $0b,$00,$00,$00,$03,$00,$00,$00,$0b,$00,$00,$00,$04,$00,$00,$00,
    $47,$00,$04,$00,$11,$00,$00,$00,$1e,$00,$00,$00,$00,$00,$00,$00,
    $47,$00,$04,$00,$15,$00,$00,$00,$1e,$00,$00,$00,$00,$00,$00,$00,
    $47,$00,$04,$00,$16,$00,$00,$00,$1e,$00,$00,$00,$01,$00,$00,$00,
    $13,$00,$02,$00,$02,$00,$00,$00,$21,$00,$03,$00,$03,$00,$00,$00,
    $02,$00,$00,$00,$16,$00,$03,$00,$06,$00,$00,$00,$20,$00,$00,$00,
    $17,$00,$04,$00,$07,$00,$00,$00,$06,$00,$00,$00,$04,$00,$00,$00,
    $15,$00,$04,$00,$08,$00,$00,$00,$20,$00,$00,$00,$00,$00,$00,$00,
    $2b,$00,$04,$00,$08,$00,$00,$00,$09,$00,$00,$00,$01,$00,$00,$00,
    $1c,$00,$04,$00,$0a,$00,$00,$00,$06,$00,$00,$00,$09,$00,$00,$00,
    $1e,$00,$06,$00,$0b,$00,$00,$00,$07,$00,$00,$00,$06,$00,$00,$00,
    $0a,$00,$00,$00,$0a,$00,$00,$00,$20,$00,$04,$00,$0c,$00,$00,$00,
    $03,$00,$00,$00,$0b,$00,$00,$00,$3b,$00,$04,$00,$0c,$00,$00,$00,
    $0d,$00,$00,$00,$03,$00,$00,$00,$15,$00,$04,$00,$0e,$00,$00,$00,
    $20,$00,$00,$00,$01,$00,$00,$00,$2b,$00,$04,$00,$0e,$00,$00,$00,
    $0f,$00,$00,$00,$00,$00,$00,$00,$20,$00,$04,$00,$10,$00,$00,$00,
    $01,$00,$00,$00,$07,$00,$00,$00,$3b,$00,$04,$00,$10,$00,$00,$00,
    $11,$00,$00,$00,$01,$00,$00,$00,$20,$00,$04,$00,$13,$00,$00,$00,
    $03,$00,$00,$00,$07,$00,$00,$00,$3b,$00,$04,$00,$13,$00,$00,$00,
    $15,$00,$00,$00,$03,$00,$00,$00,$3b,$00,$04,$00,$10,$00,$00,$00,
    $16,$00,$00,$00,$01,$00,$00,$00,$36,$00,$05,$00,$02,$00,$00,$00,
    $04,$00,$00,$00,$00,$00,$00,$00,$03,$00,$00,$00,$f8,$00,$02,$00,
    $05,$00,$00,$00,$3d,$00,$04,$00,$07,$00,$00,$00,$12,$00,$00,$00,
    $11,$00,$00,$00,$41,$00,$05,$00,$13,$00,$00,$00,$14,$00,$00,$00,
    $0d,$00,$00,$00,$0f,$00,$00,$00,$3e,$00,$03,$00,$14,$00,$00,$00,
    $12,$00,$00,$00,$3d,$00,$04,$00,$07,$00,$00,$00,$17,$00,$00,$00,
    $16,$00,$00,$00,$3e,$00,$03,$00,$15,$00,$00,$00,$17,$00,$00,$00,
    $fd,$00,$01,$00,$38,$00,$01,$00);
{$ENDIF}

(*
  #version 460

  layout(location = 0) out vec4 frag_color;
  layout(location = 0) in vec4 color;

  void main()
  {
      frag_color = color;
  }

*)
{$IFDEF SOKOL_VULKAN}
const
  FS_BYTECODE_SPIRV_VK: array [0..375] of Byte = (
    $03,$02,$23,$07,$00,$04,$01,$00,$0b,$00,$08,$00,$0d,$00,$00,$00,
    $00,$00,$00,$00,$11,$00,$02,$00,$01,$00,$00,$00,$0b,$00,$06,$00,
    $01,$00,$00,$00,$47,$4c,$53,$4c,$2e,$73,$74,$64,$2e,$34,$35,$30,
    $00,$00,$00,$00,$0e,$00,$03,$00,$00,$00,$00,$00,$01,$00,$00,$00,
    $0f,$00,$07,$00,$04,$00,$00,$00,$04,$00,$00,$00,$6d,$61,$69,$6e,
    $00,$00,$00,$00,$09,$00,$00,$00,$0b,$00,$00,$00,$10,$00,$03,$00,
    $04,$00,$00,$00,$07,$00,$00,$00,$03,$00,$03,$00,$02,$00,$00,$00,
    $cc,$01,$00,$00,$05,$00,$04,$00,$04,$00,$00,$00,$6d,$61,$69,$6e,
    $00,$00,$00,$00,$05,$00,$05,$00,$09,$00,$00,$00,$66,$72,$61,$67,
    $5f,$63,$6f,$6c,$6f,$72,$00,$00,$05,$00,$04,$00,$0b,$00,$00,$00,
    $63,$6f,$6c,$6f,$72,$00,$00,$00,$47,$00,$04,$00,$09,$00,$00,$00,
    $1e,$00,$00,$00,$00,$00,$00,$00,$47,$00,$04,$00,$0b,$00,$00,$00,
    $1e,$00,$00,$00,$00,$00,$00,$00,$13,$00,$02,$00,$02,$00,$00,$00,
    $21,$00,$03,$00,$03,$00,$00,$00,$02,$00,$00,$00,$16,$00,$03,$00,
    $06,$00,$00,$00,$20,$00,$00,$00,$17,$00,$04,$00,$07,$00,$00,$00,
    $06,$00,$00,$00,$04,$00,$00,$00,$20,$00,$04,$00,$08,$00,$00,$00,
    $03,$00,$00,$00,$07,$00,$00,$00,$3b,$00,$04,$00,$08,$00,$00,$00,
    $09,$00,$00,$00,$03,$00,$00,$00,$20,$00,$04,$00,$0a,$00,$00,$00,
    $01,$00,$00,$00,$07,$00,$00,$00,$3b,$00,$04,$00,$0a,$00,$00,$00,
    $0b,$00,$00,$00,$01,$00,$00,$00,$36,$00,$05,$00,$02,$00,$00,$00,
    $04,$00,$00,$00,$00,$00,$00,$00,$03,$00,$00,$00,$f8,$00,$02,$00,
    $05,$00,$00,$00,$3d,$00,$04,$00,$07,$00,$00,$00,$0c,$00,$00,$00,
    $0b,$00,$00,$00,$3e,$00,$03,$00,$09,$00,$00,$00,$0c,$00,$00,$00,
    $fd,$00,$01,$00,$38,$00,$01,$00);
{$ENDIF}

var
  GBufferoffsetsShaderDesc: TNativeShaderDesc;

procedure InitBufferoffsetsShaderDesc;
begin
  GBufferoffsetsShaderDesc.Init;
  
  {$IFDEF SOKOL_GLCORE}
  if (TGfx.Backend = TBackend.GLCore) then
  begin
    GBufferoffsetsShaderDesc.vertex_func.source := @VS_SOURCE_GLSL410;
    GBufferoffsetsShaderDesc.vertex_func.entry := 'main';
    GBufferoffsetsShaderDesc.fragment_func.source := @FS_SOURCE_GLSL410;
    GBufferoffsetsShaderDesc.fragment_func.entry := 'main';
    GBufferoffsetsShaderDesc.attrs[0].base_type := _SG_SHADERATTRBASETYPE_FLOAT;
    GBufferoffsetsShaderDesc.attrs[0].glsl_name := 'position';
    GBufferoffsetsShaderDesc.attrs[1].base_type := _SG_SHADERATTRBASETYPE_FLOAT;
    GBufferoffsetsShaderDesc.attrs[1].glsl_name := 'color0';
    GBufferoffsetsShaderDesc.&label := 'bufferoffsets_shader';
  end;
  {$ENDIF !SOKOL_GLCORE}
  
  {$IFDEF SOKOL_GLES3}
  if (TGfx.Backend = TBackend.Gles3) then
  begin
    GBufferoffsetsShaderDesc.vertex_func.source := @VS_SOURCE_GLSL300ES;
    GBufferoffsetsShaderDesc.vertex_func.entry := 'main';
    GBufferoffsetsShaderDesc.fragment_func.source := @FS_SOURCE_GLSL300ES;
    GBufferoffsetsShaderDesc.fragment_func.entry := 'main';
    GBufferoffsetsShaderDesc.attrs[0].base_type := _SG_SHADERATTRBASETYPE_FLOAT;
    GBufferoffsetsShaderDesc.attrs[0].glsl_name := 'position';
    GBufferoffsetsShaderDesc.attrs[1].base_type := _SG_SHADERATTRBASETYPE_FLOAT;
    GBufferoffsetsShaderDesc.attrs[1].glsl_name := 'color0';
    GBufferoffsetsShaderDesc.&label := 'bufferoffsets_shader';
  end;
  {$ENDIF !SOKOL_GLES3}
  
  {$IFDEF SOKOL_D3D11}
  if (TGfx.Backend = TBackend.D3D11) then
  begin
    GBufferoffsetsShaderDesc.vertex_func.source := @VS_SOURCE_HLSL5;
    GBufferoffsetsShaderDesc.vertex_func.d3d11_target := 'vs_5_0';
    GBufferoffsetsShaderDesc.vertex_func.entry := 'main';
    GBufferoffsetsShaderDesc.fragment_func.source := @FS_SOURCE_HLSL5;
    GBufferoffsetsShaderDesc.fragment_func.d3d11_target := 'ps_5_0';
    GBufferoffsetsShaderDesc.fragment_func.entry := 'main';
    GBufferoffsetsShaderDesc.attrs[0].base_type := _SG_SHADERATTRBASETYPE_FLOAT;
    GBufferoffsetsShaderDesc.attrs[0].hlsl_sem_name := 'TEXCOORD';
    GBufferoffsetsShaderDesc.attrs[0].hlsl_sem_index := 0;
    GBufferoffsetsShaderDesc.attrs[1].base_type := _SG_SHADERATTRBASETYPE_FLOAT;
    GBufferoffsetsShaderDesc.attrs[1].hlsl_sem_name := 'TEXCOORD';
    GBufferoffsetsShaderDesc.attrs[1].hlsl_sem_index := 1;
    GBufferoffsetsShaderDesc.&label := 'bufferoffsets_shader';
  end;
  {$ENDIF !SOKOL_D3D11}
  
  {$IFDEF SOKOL_METAL}
  if (TGfx.Backend = TBackend.MetalMacOS) then
  begin
    GBufferoffsetsShaderDesc.vertex_func.source := @VS_SOURCE_METAL_MACOS;
    GBufferoffsetsShaderDesc.vertex_func.entry := 'main0';
    GBufferoffsetsShaderDesc.fragment_func.source := @FS_SOURCE_METAL_MACOS;
    GBufferoffsetsShaderDesc.fragment_func.entry := 'main0';
    GBufferoffsetsShaderDesc.attrs[0].base_type := _SG_SHADERATTRBASETYPE_FLOAT;
    GBufferoffsetsShaderDesc.attrs[1].base_type := _SG_SHADERATTRBASETYPE_FLOAT;
    GBufferoffsetsShaderDesc.&label := 'bufferoffsets_shader';
  end;
  {$ENDIF !SOKOL_METAL}
  
  {$IFDEF SOKOL_METAL}
  if (TGfx.Backend = TBackend.MetalIOS) then
  begin
    GBufferoffsetsShaderDesc.vertex_func.source := @VS_SOURCE_METAL_IOS;
    GBufferoffsetsShaderDesc.vertex_func.entry := 'main0';
    GBufferoffsetsShaderDesc.fragment_func.source := @FS_SOURCE_METAL_IOS;
    GBufferoffsetsShaderDesc.fragment_func.entry := 'main0';
    GBufferoffsetsShaderDesc.attrs[0].base_type := _SG_SHADERATTRBASETYPE_FLOAT;
    GBufferoffsetsShaderDesc.attrs[1].base_type := _SG_SHADERATTRBASETYPE_FLOAT;
    GBufferoffsetsShaderDesc.&label := 'bufferoffsets_shader';
  end;
  {$ENDIF !SOKOL_METAL}
  
  {$IFDEF SOKOL_VULKAN}
  if (TGfx.Backend = TBackend.Vulkan) then
  begin
    GBufferoffsetsShaderDesc.vertex_func.bytecode.ptr := @VS_BYTECODE_SPIRV_VK;
    GBufferoffsetsShaderDesc.vertex_func.bytecode.size := 840;
    GBufferoffsetsShaderDesc.vertex_func.entry := 'main';
    GBufferoffsetsShaderDesc.fragment_func.bytecode.ptr := @FS_BYTECODE_SPIRV_VK;
    GBufferoffsetsShaderDesc.fragment_func.bytecode.size := 376;
    GBufferoffsetsShaderDesc.fragment_func.entry := 'main';
    GBufferoffsetsShaderDesc.attrs[0].base_type := _SG_SHADERATTRBASETYPE_FLOAT;
    GBufferoffsetsShaderDesc.attrs[1].base_type := _SG_SHADERATTRBASETYPE_FLOAT;
    GBufferoffsetsShaderDesc.&label := 'bufferoffsets_shader';
  end;
  {$ENDIF !SOKOL_VULKAN}
end;

function BufferoffsetsShaderDesc: PNativeShaderDesc;
begin
  if (GBufferoffsetsShaderDesc.&label = nil) then
    InitBufferoffsetsShaderDesc;

  Result := @GBufferoffsetsShaderDesc;
end;

end.
