unit ArrayTexShader;
{ #version:1# (machine generated, don't edit!)

  Generated by sokol-shdc (https://github.com/floooh/sokol-tools)
  With Delphi modifications (https://github.com/neslib/Neslib.Sokol.Tools)

  Cmdline: sokol-shdc --input ArrayTexShader.glsl --output ArrayTexShader.pas

  Overview:

    Shader program 'arraytex':
      Get shader desc: ArraytexShaderDesc()
      Vertex shader: vs
        Attribute slots:
          ATTR_VS_POSITION = 0
          ATTR_VS_TEXCOORD0 = 1
        Uniform block 'vs_params':
          Delphi record: TVSParams
          Bind slot: SLOT_VS_PARAMS = 0
      Fragment shader: fs
        Image 'tex':
          Type: _SG_IMAGETYPE_ARRAY
          Component Type: _SG_SAMPLERTYPE_FLOAT
          Bind slot: SLOT_TEX = 0


  Shader descriptor records:

    var ArraytexShader := TShader.Create(ArraytexShaderDesc);

  Vertex attribute locations for vertex shader 'vs':

    var PipDesc: TPipelineDesc;
    PipDesc.Init;
    PipDesc.Attrs[ATTR_VS_POSITION]. ...
    PipDesc.Attrs[ATTR_VS_TEXCOORD0]. ...
    PipDesc. ...
    var Pip := TPipeline.Create(PipDesc);

  Image bind slots, use as index in TBindings.VSImages[] or .FSImages[]:

    SLOT_TEX = 0;

  Bind slot and Delphi record for uniform block 'VSParams':

    VSParams: TVSParams;
    VSParams.Mvp := ...;
    VSParams.Offset0 := ...;
    VSParams.Offset1 := ...;
    VSParams.Offset2 := ...;
    TGfx.ApplyUniforms(TShaderStage.[VertexShader|FragmentShader], SLOT_VS_PARAMS, TRange.Create(VSParams));

}

{$INCLUDE 'Neslib.Sokol.inc'}

interface

uses
  Neslib.FastMath,
  Neslib.Sokol.Gfx;

const
  ATTR_VS_POSITION = 0;
  ATTR_VS_TEXCOORD0 = 1;

const
  SLOT_TEX = 0;

const
  SLOT_VS_PARAMS = 0;

type
  TVSParams = packed record
  public
    Mvp: TMatrix4;
    Offset0: TVector2;
    Offset1: TVector2;
    Offset2: TVector2;
    _Pad88: array [0..7] of UInt8;
  end;

function ArraytexShaderDesc: PNativeShaderDesc;

implementation

uses
  Neslib.Sokol.Api;

{$IFDEF SOKOL_GLCORE33}
const
  VS_SOURCE_GLSL330 =
    '#version 330'#10+

    'uniform vec4 vs_params[6];'#10+
    'layout(location = 0) in vec4 position;'#10+
    'out vec3 uv0;'#10+
    'layout(location = 1) in vec2 texcoord0;'#10+
    'out vec3 uv1;'#10+
    'out vec3 uv2;'#10+

    'void main()'#10+
    '{'#10+
    '    gl_Position = mat4(vs_params[0], vs_params[1], vs_params[2], vs_params[3]) * position;'#10+
    '    uv0 = vec3(texcoord0 + vs_params[4].xy, 0.0);'#10+
    '    uv1 = vec3(texcoord0 + vs_params[4].zw, 1.0);'#10+
    '    uv2 = vec3(texcoord0 + vs_params[5].xy, 2.0);'#10+
    '}';

const
  FS_SOURCE_GLSL330 =
    '#version 330'#10+

    'uniform sampler2DArray tex;'#10+

    'in vec3 uv0;'#10+
    'in vec3 uv1;'#10+
    'in vec3 uv2;'#10+
    'layout(location = 0) out vec4 frag_color;'#10+

    'void main()'#10+
    '{'#10+
    '    frag_color = vec4((texture(tex, uv0).xyz + texture(tex, uv1).xyz) + texture(tex, uv2).xyz, 1.0);'#10+
    '}';

{$ENDIF !SOKOL_GLCORE33}

{$IFDEF SOKOL_GLES2}
const
  VS_SOURCE_GLSL100 =
    '#version 100'#10+

    'uniform vec4 vs_params[6];'#10+
    'attribute vec4 position;'#10+
    'varying vec3 uv0;'#10+
    'attribute vec2 texcoord0;'#10+
    'varying vec3 uv1;'#10+
    'varying vec3 uv2;'#10+

    'void main()'#10+
    '{'#10+
    '    gl_Position = mat4(vs_params[0], vs_params[1], vs_params[2], vs_params[3]) * position;'#10+
    '    uv0 = vec3(texcoord0 + vs_params[4].xy, 0.0);'#10+
    '    uv1 = vec3(texcoord0 + vs_params[4].zw, 1.0);'#10+
    '    uv2 = vec3(texcoord0 + vs_params[5].xy, 2.0);'#10+
    '}';

const
  FS_SOURCE_GLSL100 =
    '#version 100'#10+
    'precision mediump float;'#10+
    'precision highp int;'#10+

    'uniform highp sampler2DArray tex;'#10+

    'varying highp vec3 uv0;'#10+
    'varying highp vec3 uv1;'#10+
    'varying highp vec3 uv2;'#10+

    'void main()'#10+
    '{'#10+
    '    gl_FragData[0] = vec4((texture2D(tex, uv0).xyz + texture2D(tex, uv1).xyz) + texture2D(tex, uv2).xyz, 1.0);'#10+
    '}';

{$ENDIF !SOKOL_GLES2}

{$IFDEF SOKOL_GLES3}
const
  VS_SOURCE_GLSL300ES =
    '#version 300 es'#10+

    'uniform vec4 vs_params[6];'#10+
    'layout(location = 0) in vec4 position;'#10+
    'out vec3 uv0;'#10+
    'layout(location = 1) in vec2 texcoord0;'#10+
    'out vec3 uv1;'#10+
    'out vec3 uv2;'#10+

    'void main()'#10+
    '{'#10+
    '    gl_Position = mat4(vs_params[0], vs_params[1], vs_params[2], vs_params[3]) * position;'#10+
    '    uv0 = vec3(texcoord0 + vs_params[4].xy, 0.0);'#10+
    '    uv1 = vec3(texcoord0 + vs_params[4].zw, 1.0);'#10+
    '    uv2 = vec3(texcoord0 + vs_params[5].xy, 2.0);'#10+
    '}';

const
  FS_SOURCE_GLSL300ES =
    '#version 300 es'#10+
    'precision mediump float;'#10+
    'precision highp int;'#10+

    'uniform highp sampler2DArray tex;'#10+

    'in highp vec3 uv0;'#10+
    'in highp vec3 uv1;'#10+
    'in highp vec3 uv2;'#10+
    'layout(location = 0) out highp vec4 frag_color;'#10+

    'void main()'#10+
    '{'#10+
    '    frag_color = vec4((texture(tex, uv0).xyz + texture(tex, uv1).xyz) + texture(tex, uv2).xyz, 1.0);'#10+
    '}';

{$ENDIF !SOKOL_GLES3}

{$IFDEF SOKOL_D3D11}
const
  VS_SOURCE_HLSL5 =
    'cbuffer vs_params : register(b0)'#10+
    '{'#10+
    '    row_major float4x4 _22_mvp : packoffset(c0);'#10+
    '    float2 _22_offset0 : packoffset(c4);'#10+
    '    float2 _22_offset1 : packoffset(c4.z);'#10+
    '    float2 _22_offset2 : packoffset(c5);'#10+
    '};'#10+


    'static float4 gl_Position;'#10+
    'static float4 position;'#10+
    'static float3 uv0;'#10+
    'static float2 texcoord0;'#10+
    'static float3 uv1;'#10+
    'static float3 uv2;'#10+

    'struct SPIRV_Cross_Input'#10+
    '{'#10+
    '    float4 position : TEXCOORD0;'#10+
    '    float2 texcoord0 : TEXCOORD1;'#10+
    '};'#10+

    'struct SPIRV_Cross_Output'#10+
    '{'#10+
    '    float3 uv0 : TEXCOORD0;'#10+
    '    float3 uv1 : TEXCOORD1;'#10+
    '    float3 uv2 : TEXCOORD2;'#10+
    '    float4 gl_Position : SV_Position;'#10+
    '};'#10+

    'void vert_main()'#10+
    '{'#10+
    '    gl_Position = mul(position, _22_mvp);'#10+
    '    uv0 = float3(texcoord0 + _22_offset0, 0.0f);'#10+
    '    uv1 = float3(texcoord0 + _22_offset1, 1.0f);'#10+
    '    uv2 = float3(texcoord0 + _22_offset2, 2.0f);'#10+
    '}'#10+

    'SPIRV_Cross_Output main(SPIRV_Cross_Input stage_input)'#10+
    '{'#10+
    '    position = stage_input.position;'#10+
    '    texcoord0 = stage_input.texcoord0;'#10+
    '    vert_main();'#10+
    '    SPIRV_Cross_Output stage_output;'#10+
    '    stage_output.gl_Position = gl_Position;'#10+
    '    stage_output.uv0 = uv0;'#10+
    '    stage_output.uv1 = uv1;'#10+
    '    stage_output.uv2 = uv2;'#10+
    '    return stage_output;'#10+
    '}';

const
  FS_SOURCE_HLSL5 =
    'Texture2DArray<float4> tex : register(t0);'#10+
    'SamplerState _tex_sampler : register(s0);'#10+

    'static float3 uv0;'#10+
    'static float3 uv1;'#10+
    'static float3 uv2;'#10+
    'static float4 frag_color;'#10+

    'struct SPIRV_Cross_Input'#10+
    '{'#10+
    '    float3 uv0 : TEXCOORD0;'#10+
    '    float3 uv1 : TEXCOORD1;'#10+
    '    float3 uv2 : TEXCOORD2;'#10+
    '};'#10+

    'struct SPIRV_Cross_Output'#10+
    '{'#10+
    '    float4 frag_color : SV_Target0;'#10+
    '};'#10+

    'void frag_main()'#10+
    '{'#10+
    '    frag_color = float4((tex.Sample(_tex_sampler, uv0).xyz + tex.Sample(_tex_sampler, uv1).xyz) + tex.Sample(_tex_sampler, uv2).xyz, 1.0f);'#10+
    '}'#10+

    'SPIRV_Cross_Output main(SPIRV_Cross_Input stage_input)'#10+
    '{'#10+
    '    uv0 = stage_input.uv0;'#10+
    '    uv1 = stage_input.uv1;'#10+
    '    uv2 = stage_input.uv2;'#10+
    '    frag_main();'#10+
    '    SPIRV_Cross_Output stage_output;'#10+
    '    stage_output.frag_color = frag_color;'#10+
    '    return stage_output;'#10+
    '}';

{$ENDIF !SOKOL_D3D11}

{$IFDEF SOKOL_METAL}
const
  VS_SOURCE_METAL_MACOS =
    '#include <metal_stdlib>'#10+
    '#include <simd/simd.h>'#10+

    'using namespace metal;'#10+

    'struct vs_params'#10+
    '{'#10+
    '    float4x4 mvp;'#10+
    '    float2 offset0;'#10+
    '    float2 offset1;'#10+
    '    float2 offset2;'#10+
    '};'#10+

    'struct main0_out'#10+
    '{'#10+
    '    float3 uv0 [[user(locn0)]];'#10+
    '    float3 uv1 [[user(locn1)]];'#10+
    '    float3 uv2 [[user(locn2)]];'#10+
    '    float4 gl_Position [[position]];'#10+
    '};'#10+

    'struct main0_in'#10+
    '{'#10+
    '    float4 position [[attribute(0)]];'#10+
    '    float2 texcoord0 [[attribute(1)]];'#10+
    '};'#10+

    'vertex main0_out main0(main0_in in [[stage_in]], constant vs_params& _22 [[buffer(0)]])'#10+
    '{'#10+
    '    main0_out out = {};'#10+
    '    out.gl_Position = _22.mvp * in.position;'#10+
    '    out.uv0 = float3(in.texcoord0 + _22.offset0, 0.0);'#10+
    '    out.uv1 = float3(in.texcoord0 + _22.offset1, 1.0);'#10+
    '    out.uv2 = float3(in.texcoord0 + _22.offset2, 2.0);'#10+
    '    return out;'#10+
    '}';

const
  FS_SOURCE_METAL_MACOS =
    '#include <metal_stdlib>'#10+
    '#include <simd/simd.h>'#10+

    'using namespace metal;'#10+

    'struct main0_out'#10+
    '{'#10+
    '    float4 frag_color [[color(0)]];'#10+
    '};'#10+

    'struct main0_in'#10+
    '{'#10+
    '    float3 uv0 [[user(locn0)]];'#10+
    '    float3 uv1 [[user(locn1)]];'#10+
    '    float3 uv2 [[user(locn2)]];'#10+
    '};'#10+

    'fragment main0_out main0(main0_in in [[stage_in]], texture2d_array<float> tex [[texture(0)]], sampler texSmplr [[sampler(0)]])'#10+
    '{'#10+
    '    main0_out out = {};'#10+
    '    out.frag_color = float4((tex.sample(texSmplr, in.uv0.xy, uint(round(in.uv0.z))).xyz + tex.sample(texSmplr, in.uv1.xy, uint(round(in.uv1.z))).xyz) + tex.sample(texSmplr, in.uv2.xy, '+
      'uint(round(in.uv2.z))).xyz, 1.0);'#10+
    '    return out;'#10+
    '}';

{$ENDIF !SOKOL_METAL}

{$IFDEF SOKOL_METAL}
const
  VS_SOURCE_METAL_IOS =
    '#include <metal_stdlib>'#10+
    '#include <simd/simd.h>'#10+

    'using namespace metal;'#10+

    'struct vs_params'#10+
    '{'#10+
    '    float4x4 mvp;'#10+
    '    float2 offset0;'#10+
    '    float2 offset1;'#10+
    '    float2 offset2;'#10+
    '};'#10+

    'struct main0_out'#10+
    '{'#10+
    '    float3 uv0 [[user(locn0)]];'#10+
    '    float3 uv1 [[user(locn1)]];'#10+
    '    float3 uv2 [[user(locn2)]];'#10+
    '    float4 gl_Position [[position]];'#10+
    '};'#10+

    'struct main0_in'#10+
    '{'#10+
    '    float4 position [[attribute(0)]];'#10+
    '    float2 texcoord0 [[attribute(1)]];'#10+
    '};'#10+

    'vertex main0_out main0(main0_in in [[stage_in]], constant vs_params& _22 [[buffer(0)]])'#10+
    '{'#10+
    '    main0_out out = {};'#10+
    '    out.gl_Position = _22.mvp * in.position;'#10+
    '    out.uv0 = float3(in.texcoord0 + _22.offset0, 0.0);'#10+
    '    out.uv1 = float3(in.texcoord0 + _22.offset1, 1.0);'#10+
    '    out.uv2 = float3(in.texcoord0 + _22.offset2, 2.0);'#10+
    '    return out;'#10+
    '}';

const
  FS_SOURCE_METAL_IOS =
    '#include <metal_stdlib>'#10+
    '#include <simd/simd.h>'#10+

    'using namespace metal;'#10+

    'struct main0_out'#10+
    '{'#10+
    '    float4 frag_color [[color(0)]];'#10+
    '};'#10+

    'struct main0_in'#10+
    '{'#10+
    '    float3 uv0 [[user(locn0)]];'#10+
    '    float3 uv1 [[user(locn1)]];'#10+
    '    float3 uv2 [[user(locn2)]];'#10+
    '};'#10+

    'fragment main0_out main0(main0_in in [[stage_in]], texture2d_array<float> tex [[texture(0)]], sampler texSmplr [[sampler(0)]])'#10+
    '{'#10+
    '    main0_out out = {};'#10+
    '    out.frag_color = float4((tex.sample(texSmplr, in.uv0.xy, uint(round(in.uv0.z))).xyz + tex.sample(texSmplr, in.uv1.xy, uint(round(in.uv1.z))).xyz) + tex.sample(texSmplr, in.uv2.xy, '+
      'uint(round(in.uv2.z))).xyz, 1.0);'#10+
    '    return out;'#10+
    '}';

{$ENDIF !SOKOL_METAL}

var
  GArraytexShaderDesc: TNativeShaderDesc;

procedure InitArraytexShaderDesc;
begin
  GArraytexShaderDesc.Init;
  GArraytexShaderDesc.Attrs[0].Init('position', 'TEXCOORD', 0);
  GArraytexShaderDesc.Attrs[1].Init('texcoord0', 'TEXCOORD', 1);

  case TGfx.Backend of
    {$IFDEF SOKOL_GLCORE33}
    TBackend.GLCore33:
      begin
        GArraytexShaderDesc.VS.Source := VS_SOURCE_GLSL330;
        GArraytexShaderDesc.FS.Source := FS_SOURCE_GLSL330;
      end;
    {$ENDIF}

    {$IFDEF SOKOL_GLES2}
    TBackend.Gles2:
      begin
        GArraytexShaderDesc.VS.Source := VS_SOURCE_GLSL100;
        GArraytexShaderDesc.FS.Source := FS_SOURCE_GLSL100;
      end;
    {$ENDIF}

    {$IFDEF SOKOL_GLES3}
    TBackend.Gles3:
      begin
        GArraytexShaderDesc.VS.Source := VS_SOURCE_GLSL300ES;
        GArraytexShaderDesc.FS.Source := FS_SOURCE_GLSL300ES;
      end;
    {$ENDIF}

    {$IFDEF SOKOL_D3D11}
    TBackend.D3D11:
      begin
        GArraytexShaderDesc.VS.Source := VS_SOURCE_HLSL5;
        GArraytexShaderDesc.FS.Source := FS_SOURCE_HLSL5;
      end;
    {$ENDIF}

    {$IFDEF SOKOL_METAL}
    TBackend.MetalMacOS:
      begin
        GArraytexShaderDesc.VS.Source := VS_SOURCE_METAL_MACOS;
        GArraytexShaderDesc.FS.Source := FS_SOURCE_METAL_MACOS;
      end;
    {$ENDIF}

    {$IFDEF SOKOL_METAL}
    TBackend.MetalIOS:
      begin
        GArraytexShaderDesc.VS.Source := VS_SOURCE_METAL_IOS;
        GArraytexShaderDesc.FS.Source := FS_SOURCE_METAL_IOS;
      end;
    {$ENDIF}
  else
    Assert(False)
  end;

  GArraytexShaderDesc.vs.uniform_blocks[0].size := 96;
  GArraytexShaderDesc.vs.uniform_blocks[0].layout := _SG_UNIFORMLAYOUT_STD140;
  if (TGfx.Backend.IsGL) then
    GArraytexShaderDesc.vs.uniform_blocks[0].uniforms[0].Init('vs_params', _SG_UNIFORMTYPE_FLOAT4, 6);
  GArraytexShaderDesc.fs.images[0].Init('tex', _SG_IMAGETYPE_ARRAY, _SG_SAMPLERTYPE_FLOAT);
  GArraytexShaderDesc.&label := 'ArraytexShader';
end;

function ArraytexShaderDesc: PNativeShaderDesc;
begin
  if (GArraytexShaderDesc.VS.Entry = nil) then
    InitArraytexShaderDesc;

  Result := @GArraytexShaderDesc;
end;

end.
